$defs:
  chat-message:
    properties:
      content:
        $ref: schema.yaml#/$defs/instill-types/multi-modal-content
        description: The message content.
        uiOrder: 1
        title: Content
      role:
        description: The message role, i.e. 'system', 'user' or 'assistant'.
        uiOrder: 0
        title: Role
        type: string
    required:
      - role
      - content
    title: Chat Message
    type: object
  common:
    description: Input.
    uiOrder: 0
    properties:
      image-base64:
        description: Image base64.
        type: string
        uiOrder: 2
        title: Image
      model-name:
        description: The Instill Model model to be used.
        type: string
        uiOrder: 0
        title: Model Name
    required:
      - image-base64
      - model-name
    title: Input
    type: object
TASK_CLASSIFICATION:
  shortDescription: Classify images into predefined categories.
  input:
    $ref: '#/$defs/common'
    type: object
  output:
    $ref: schema.yaml#/$defs/instill-types/classification
    description: Output.
    uiOrder: 0
    title: Output
    type: object
TASK_DETECTION:
  shortDescription: Detect and localize multiple objects in images.
  input:
    $ref: '#/$defs/common'
    type: object
  output:
    $ref: schema.yaml#/$defs/instill-types/detection
    description: Output.
    uiOrder: 0
    title: Output
    type: object
TASK_INSTANCE_SEGMENTATION:
  shortDescription: Detect, localize and delineate multiple objects in images.
  input:
    $ref: '#/$defs/common'
    type: object
  output:
    $ref: schema.yaml#/$defs/instill-types/instance-segmentation
    description: Output.
    uiOrder: 0
    title: Output
    type: object
TASK_KEYPOINT:
  shortDescription: Detect and localize multiple keypoints of objects in images.
  input:
    $ref: '#/$defs/common'
    type: object
  output:
    $ref: schema.yaml#/$defs/instill-types/keypoint
    description: Output.
    uiOrder: 0
    title: Output
    type: object
TASK_OCR:
  shortDescription: Detect and recognize text in images.
  input:
    $ref: '#/$defs/common'
    type: object
  output:
    $ref: schema.yaml#/$defs/instill-types/ocr
    description: Output.
    uiOrder: 0
    title: Output
    type: object
TASK_SEMANTIC_SEGMENTATION:
  shortDescription: Classify image pixels into predefined categories.
  input:
    $ref: '#/$defs/common'
    type: object
  output:
    $ref: schema.yaml#/$defs/instill-types/semantic-segmentation
    description: Output.
    uiOrder: 0
    title: Output
    type: object
TASK_TEXT_GENERATION:
  shortDescription: Generate texts from input text prompts.
  input:
    description: Input.
    uiOrder: 0
    properties:
      max-new-tokens:
        default: 50
        description: The maximum number of tokens for model to generate.
        type: integer
        uiOrder: 6
        title: Max New Tokens
      model-name:
        description: The Instill Model model to be used.
        type: string
        uiOrder: 0
        title: Model Name
      prompt:
        description: The prompt text.
        type: string
        uiOrder: 2
        title: Prompt
      seed:
        description: The seed.
        type: integer
        uiOrder: 4
        title: Seed
      system-message:
        default: You are a helpful assistant.
        description: The system message helps set the behavior of the assistant. For example, you can modify the personality of the assistant or provide
          specific instructions about how it should behave throughout the conversation. By default, the model’s behavior is using a generic message as "You
          are a helpful assistant.".
        type: string
        shortDescription: The system message helps set the behavior of the assistant
        uiOrder: 2
        title: System Message
      temperature:
        default: 0.7
        description: The temperature for sampling.
        type: number
        uiOrder: 5
        title: Temperature
    required:
      - prompt
      - model-name
    title: Input
    type: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      text:
        description: Text.
        uiOrder: 0
        title: Text
        type: string
    required:
      - text
    title: Output
    type: object
TASK_TEXT_GENERATION_CHAT:
  shortDescription: Generate texts from input text prompts and chat history.
  input:
    description: Input.
    uiOrder: 0
    properties:
      chat-history:
        description: 'Incorporate external chat history, specifically previous messages within the conversation. Please note that System Message will be
          ignored and will not have any effect when this field is populated. Each message should adhere to the format: {"role": "The message role, i.e.
          ''system'', ''user'' or ''assistant''", "content": "message content"}.'
        type: array
        shortDescription: 'Incorporate external chat history, specifically previous messages within the conversation. Please note that System Message will
          be ignored and will not have any effect when this field is populated. Each message should adhere to the format: {"role": "The message role, i.e.
          ''system'', ''user'' or ''assistant''", "content": "message content"}.'
        uiOrder: 4
        items:
          $ref: '#/$defs/chat-message'
        title: Chat history
      max-new-tokens:
        default: 50
        description: The maximum number of tokens for model to generate.
        type: integer
        uiOrder: 6
        title: Max New Tokens
      model-name:
        description: The Instill Model model to be used.
        type: string
        uiOrder: 0
        title: Model Name
      prompt:
        description: The prompt text.
        type: string
        uiOrder: 2
        title: Prompt
      prompt-images:
        description: The prompt images.
        type: array
        uiOrder: 3
        items:
          type: string
        title: Prompt Images
      seed:
        description: The seed.
        type: integer
        uiOrder: 4
        title: Seed
      system-message:
        default: You are a helpful assistant.
        description: The system message helps set the behavior of the assistant. For example, you can modify the personality of the assistant or provide
          specific instructions about how it should behave throughout the conversation. By default, the model’s behavior is using a generic message as "You
          are a helpful assistant.".
        type: string
        shortDescription: The system message helps set the behavior of the assistant
        uiOrder: 2
        title: System Message
      temperature:
        default: 0.7
        description: The temperature for sampling.
        type: number
        uiOrder: 5
        title: Temperature
    required:
      - prompt
      - model-name
    title: Input
    type: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      text:
        description: Text.
        uiOrder: 0
        title: Text
        type: string
    required:
      - text
    title: Output
    type: object
TASK_TEXT_TO_IMAGE:
  shortDescription: Generate images from input text prompts.
  input:
    description: Input.
    uiOrder: 0
    properties:
      model-name:
        description: The Instill Model model to be used.
        type: string
        uiOrder: 0
        title: Model Name
      prompt:
        description: The prompt text.
        type: string
        uiOrder: 2
        title: Prompt
      samples:
        description: The number of generated samples, default is 1.
        type: integer
        uiOrder: 5
        title: Samples
      seed:
        description: The seed, default is 0.
        type: integer
        uiOrder: 6
        title: Seed
      negative-prompt:
        title: Aspect ratio
        description: Keywords of what you do not wish to see in the output image.
        shortDescription: Keywords of what you do not wish to see in the output image.
        type: string
        uiOrder: 7
      aspect-ratio:
        title: Aspect ratio
        description: Controls the aspect ratio of the generated image. Defaults to 1:1.
        shortDescription: Controls the aspect ratio of the generated image. Defaults to 1:1.
        type: string
        uiOrder: 8
        default: '1:1'
        enum:
          - '16:9'
          - '1:1'
          - '21:9'
          - '2:3'
          - '3:2'
          - '4:5'
          - '5:4'
          - '9:16'
          - '9:21'
    required:
      - prompt
      - model-name
    title: Input
    type: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      images:
        description: Images.
        uiOrder: 0
        items:
          title: Image
          type: image/jpeg
        title: Images
        type: array
    required:
      - images
    title: Output
    type: object
TASK_VISUAL_QUESTION_ANSWERING:
  shortDescription: Answer questions based on a prompt and an image.
  $ref: '#/TASK_TEXT_GENERATION_CHAT'
TASK_CHAT:
  shortDescription: Generate texts from input text prompts and chat history.
  $ref: '#/TASK_TEXT_GENERATION_CHAT'
TASK_EMBEDDING:
  title: Embedding
  shortDescription: This task refers to the process of generating vector embeddings from input data, which can be text or images. This transformation converts
    the data into a dense, fixed-length numerical representation that captures the essential features of the original input. These embeddings are typically
    used in machine learning tasks to represent complex data in a more structured, simplified form.
  input:
    title: Embedding Input
    description: Input schema of the embedding task.
    shortDescription: Input schema of the embedding task.
    properties:
      data:
        description: Input data.
        shortDescription: Input data.
        properties:
          model:
            description: The model to be used for generating embeddings. It should be `namespace/model-name/version`. i.e. `abrc/yolov7-stomata/v0.1.0`.
              You can see the version from the Versions tab of Model page.
            shortDescription: The model to be used.
            type: string
            uiOrder: 0
            title: Model
          embeddings:
            title: Embeddings
            items:
              oneOf:
                - properties:
                    text:
                      title: Text Content
                      description: When the input is text, the raw text is tokenized and processed into a dense, fixed-length vector that captures semantic
                        information such as word meanings and relationships. These text embeddings enable tasks like sentiment analysis, search, or classification.
                      shortDescription: Text content.
                      type: string
                      uiOrder: 1
                    type:
                      title: Text
                      description: Text input content type.
                      shortDescription: Text input content type.
                      type: string
                      const: text
                      uiOrder: 0
                  title: Text
                  required:
                    - text
                    - type
                  type: object
                - properties:
                    image-url:
                      title: Image URL
                      description: When the input is an image from a URL, the image is first fetched from the URL and then decoded into its original format.
                        It is then processed into a fixed-length vector representing essential visual features like shapes and colors. These image embeddings
                        are useful for tasks like image classification or similarity search, providing structured numerical data for complex visual inputs.
                      shortDescription: Image content URL.
                      type: string
                      uiOrder: 1
                    type:
                      title: Image URL
                      description: Image URL input content type.
                      shortDescription: Image URL input content type
                      type: string
                      const: image-url
                      uiOrder: 0
                  title: Image URL
                  required:
                    - image-url
                    - type
                  type: object
                - properties:
                    image-base64:
                      title: Image File
                      description: When the input is an image in base64 format, the base64-encoded data is first decoded into its original image form. The
                        image is then processed and transformed into a dense, fixed-length numerical vector, capturing key visual features like shapes,
                        colors, or textures.
                      shortDescription: Image file input.
                      type: string
                      uiOrder: 1
                    type:
                      title: Image File
                      description: Image file input content type.
                      shortDescription: Image file input content type.
                      type: string
                      const: image-base64
                      uiOrder: 0
                  title: Image Base64
                  required:
                    - image-base64
                    - type
                  type: object
              title: Embedding
              description: Input data to be embedded.
              uiOrder: 0
              required:
                - type
              type: object
            description: List of input data to be embedded.
            uiOrder: 1
            type: array
        required:
          - model
          - embeddings
        uiOrder: 0
        title: Data
        type: object
      parameter:
        description: Input parameter.
        shortDescription: Input parameter.
        properties:
          format:
            title: Data Format
            description: The data format of the embeddings. Defaults to float.
            shortDescription: Data format
            type: string
            enum:
              - float
              - base64
            default: float
            uiOrder: 0
          dimensions:
            title: Dimensions
            description: Number of dimensions in the output embedding vectors.
            shortDescription: Number of dimensions
            type: integer
            default: 512
            uiOrder: 1
          input-type:
            title: Input Type
            description: The type of input data to be embedded (e.g., query, document).
            shortDescription: Type of input data
            type: string
            uiOrder: 2
          truncate:
            title: Truncate
            description: How to handle inputs longer than the max token length. Defaults to 'End'.
            shortDescription: Truncation handling
            type: string
            enum:
              - None
              - End
              - Start
            default: End
            uiOrder: 3
        title: Parameter
        uiOrder: 1
        required: []
        type: object
    required:
      - data
    type: object
  output:
    title: Embedding Output
    description: Output schema of the embedding task.
    shortDescription: Output schema of the embedding task.
    properties:
      data:
        description: Output data.
        shortDescription: Output data.
        properties:
          embeddings:
            title: Embeddings
            description: List of generated embeddings.
            shortDescription: List of embeddings.
            items:
              properties:
                index:
                  title: Index
                  description: The index of the embedding vector in the array.
                  shortDescription: Index in the array
                  uiOrder: 0
                  type: integer
                vector:
                  title: Embedding Vector
                  description: The embedding vector.
                  shortDescription: Embedding vector.
                  items:
                    type: number
                  uiOrder: 1
                  type: array
                created:
                  title: Created
                  description: The Unix timestamp (in seconds) of when the embedding was created.
                  shortDescription: Timestamp of creation
                  uiOrder: 2
                  type: integer
              required:
                - index
                - vector
                - created
              type: object
            uiOrder: 0
            type: array
        required:
          - embeddings
        uiOrder: 0
        title: Data
        type: object
    required:
      - data
    type: object
