$defs:
  inputWithBody:
    uiOrder: 0
    properties:
      body:
        description: The request body.
        type: '*'
        shortDescription: The request body
        uiOrder: 1
        order: 1
        required: []
        title: Body
      endpoint-url:
        description: The API endpoint url.
        type: string
        uiOrder: 0
        title: Endpoint Url
      output-body-schema:
        description: The JSON schema of output body.
        type: string
        shortDescription: The JSON schema of output body
        uiOrder: 1
        order: 2
        required: []
        title: Body
    required:
      - endpoint-url
    title: Input
    type: object
  inputWithoutBody:
    uiOrder: 0
    properties:
      endpoint-url:
        description: The API endpoint url.
        type: string
        uiOrder: 0
        title: Endpoint Url
      output-body-schema:
        description: The request body.
        type: string
        shortDescription: The request body
        uiOrder: 1
        order: 1
        required: []
        title: Body
      header:
        description: |-
          The request HTTP headers. It must be an object where the values are
          an array of strings.
        uiOrder: 2
        order: 2
        required: []
        title: Header
        type: json
        example:
          Extra-Header-One:
            - myHeaderValue
          Extra-Header-Two:
            - val1
            - val2
    required:
      - endpoint-url
    title: Input Without Body
    type: object
  output:
    description: The HTTP response from the API.
    uiOrder: 0
    properties:
      body:
        description: The body of the response.
        uiOrder: 1
        required: []
        title: Body
        type: '*'
      header:
        description: The HTTP header of the response.
        uiOrder: 2
        required: []
        title: Header
        type: json
      status-code:
        description: The HTTP status code of the response.
        uiOrder: 0
        title: Status Code
        type: integer
    required:
      - status-code
      - body
      - header
    title: Output
    type: object
TASK_DELETE:
  shortDescription: Send a HTTP DELETE request.
  input:
    $ref: '#/$defs/inputWithBody'
  output:
    $ref: '#/$defs/output'
TASK_GET:
  shortDescription: Send a HTTP GET request.
  input:
    $ref: '#/$defs/inputWithoutBody'
  output:
    $ref: '#/$defs/output'
TASK_HEAD:
  shortDescription: Send a HTTP HEAD request.
  input:
    $ref: '#/$defs/inputWithoutBody'
  output:
    $ref: '#/$defs/output'
TASK_OPTIONS:
  shortDescription: Send a HTTP OPTIONS request.
  input:
    $ref: '#/$defs/inputWithBody'
  output:
    $ref: '#/$defs/output'
TASK_PATCH:
  shortDescription: Send a HTTP PATCH request.
  input:
    $ref: '#/$defs/inputWithBody'
  output:
    $ref: '#/$defs/output'
TASK_POST:
  shortDescription: Send a HTTP POST request.
  input:
    $ref: '#/$defs/inputWithBody'
  output:
    $ref: '#/$defs/output'
TASK_PUT:
  shortDescription: Send a HTTP PUT request.
  input:
    $ref: '#/$defs/inputWithBody'
  output:
    $ref: '#/$defs/output'
