ARG GOLANG_VERSION
FROM golang:${GOLANG_VERSION}

ARG SERVICE_NAME

WORKDIR /${SERVICE_NAME}

# -- install 3rd-party

ARG TARGETOS TARGETARCH K6_VERSION

# Install Python, create virtual environment, and install pdfplumber
RUN apt update && \
    apt install -y python3 python3-venv poppler-utils wv unrtf tidy tesseract-ocr libtesseract-dev && \
    python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install pdfplumber && \
    rm -rf /var/lib/apt/lists/*

# air
RUN --mount=target=. --mount=type=cache,target=/root/.cache/go-build --mount=type=cache,target=/go/pkg GOOS=$TARGETOS GOARCH=$TARGETARCH go install github.com/cosmtrek/air@v1.49

# k6
ADD https://github.com/grafana/k6/releases/download/v${K6_VERSION}/k6-v${K6_VERSION}-linux-$TARGETARCH.tar.gz k6-v${K6_VERSION}-linux-$TARGETARCH.tar.gz
RUN tar -xf k6-v${K6_VERSION}-linux-$TARGETARCH.tar.gz --strip-components 1 -C /usr/bin

# -- set up Go

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN chown -R nobody:nogroup /go
ENV GOCACHE /go/.cache/go-build
ENV GOENV /go/.config/go/env

USER nobody:nogroup

ENTRYPOINT ["tail", "-f", "/dev/null"]
