additionalProperties: false
properties:
  token:
    description: Fill in your HubSpot private app access token. Go here for [more information](https://developers.hubspot.com/docs/api/private-apps).
    type: string
    instillSecret: true
    uiOrder: 0
    title: Token
required:
  - token
title: HubSpot Connection
type: object
