additionalProperties: false
properties:
  api-key:
    description: Fill in your Anthropic API key. To find your keys, visit the Anthropic console page.
    type: string
    instillSecret: true
    instillCredential: true
    uiOrder: 0
    title: API Key
required: []
title: Anthropic Connection
type: object
