additionalProperties: false
properties:
  api-key:
    description: Fill in your Anthropic API key. To find your keys, visit the Anthropic
      console page.
    acceptFormats:
    - string
    instillSecret: true
    instillCredential: true
    uiOrder: 0
    title: API Key
    format: string
required: []
title: Anthropic Connection
format: object
