custom: false
documentationUrl: https://www.instill.tech/docs/component/operator/image
icon: assets/image.svg
iconUrl: ''
id: image
public: true
spec: {}
title: Image
type: COMPONENT_TYPE_OPERATOR
uid: e9eb8fc8-f249-4e11-ad50-5035d79ffc18
version: 0.1.0
sourceUrl: https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/operator/image/v0
description: Manipulate image files.
releaseStage: RELEASE_STAGE_ALPHA
