TASK_CONCAT:
  shortDescription: Concatenate images horizontally or vertically. All images must
    have the same width and height. If `grid-width` and `grid-height` are not provided,
    the images will be concatenated to a square grid.
  input:
    description: Input.
    uiOrder: 0
    properties:
      images:
        description: Input images.
        acceptFormats:
        - array
        uiOrder: 0
        title: Images
        format: array
      grid-width:
        description: Grid width. If `grid-width` is provided, `grid-height` will be
          ignored.
        acceptFormats:
        - integer
        uiOrder: 1
        title: Grid Width
        format: integer
      grid-height:
        description: Grid height. If `grid-height` is provided, `grid-width` will
          be ignored.
        acceptFormats:
        - integer
        uiOrder: 2
        title: Grid Height
        format: integer
      padding:
        description: Padding between images. If `padding` is provided, it will be
          applied to all four sides of the image.
        acceptFormats:
        - integer
        uiOrder: 3
        title: Padding
        format: integer
    required:
    - images
    title: Input
    format: object
  output:
    description: Output concatenated image.
    uiOrder: 0
    properties:
      image:
        description: Output image.
        uiOrder: 0
        title: Image
        format: image/png
    required:
    - image
    title: Output
    format: object
TASK_CROP:
  shortDescription: Crop image to the specified size.
  input:
    description: Input.
    uiOrder: 0
    properties:
      image:
        description: Input image.
        acceptFormats:
        - image/*
        uiOrder: 0
        title: Image
        format: string
      corner-radius:
        description: Radius from the corner of the image to crop the image. If `corner-radius`
          is provided, `circle-radius` will be ignored. If the `corner-radius` is
          larger than half of min(width, height), the min(width, height) will be applied
          to `corner-radius` .
        acceptFormats:
        - integer
        uiOrder: 1
        title: Corner Radius
        format: integer
      circle-radius:
        description: Radius from the center of the circle to crop the image. If `circle-radius`
          is provided, `corner-radius` will be ignored. If the `circle-radius` is
          larger than half of min(width, height), the min(width, height) will be applied
          to `circle-radius`.
        acceptFormats:
        - integer
        uiOrder: 2
        title: Circle Radius
        format: integer
      top-offset:
        description: Top offset of the crop.
        acceptFormats:
        - integer
        uiOrder: 3
        title: Top Offset
        format: integer
      right-offset:
        description: Right offset of the crop.
        acceptFormats:
        - integer
        uiOrder: 4
        title: Right Offset
        format: integer
      bottom-offset:
        description: Bottom offset of the crop.
        acceptFormats:
        - integer
        uiOrder: 5
        title: Bottom Offset
        format: integer
      left-offset:
        description: Left offset of the crop.
        acceptFormats:
        - integer
        uiOrder: 6
        title: Left Offset
        format: integer
    required:
    - image
    title: Input
    format: object
  output:
    description: Output cropped image.
    uiOrder: 0
    properties:
      image:
        description: Output image.
        uiOrder: 0
        title: Image
        format: image/png
    required:
    - image
    title: Output
    format: object
TASK_RESIZE:
  shortDescription: Resize image to the specified size.
  input:
    description: Input.
    uiOrder: 0
    properties:
      image:
        description: Input image.
        acceptFormats:
        - image/*
        uiOrder: 0
        title: Image
        format: string
      ratio:
        description: Resize ratio (e.g., 0.5 for half size, 2 for double size) to
          resize the image. If ratio is provided, width and height will be ignored.
        acceptFormats:
        - number
        uiOrder: 1
        title: Ratio
        format: number
      width:
        description: Width of the output image.
        acceptFormats:
        - integer
        uiOrder: 2
        title: Width
        format: integer
      height:
        description: Height of the output image.
        acceptFormats:
        - integer
        uiOrder: 3
        title: Height
        format: integer
    required:
    - image
    title: Input
    format: object
  output:
    description: Output resized image.
    uiOrder: 0
    properties:
      image:
        description: Output image.
        uiOrder: 0
        title: Image
        format: image/png
    required:
    - image
    title: Output
    format: object
TASK_DRAW_CLASSIFICATION:
  shortDescription: Draw classification result on the image.
  input:
    description: Input.
    uiOrder: 0
    properties:
      category:
        $ref: schema.yaml#/$defs/instill-types/classification/properties/category
        acceptFormats:
        - string
      image:
        description: Input image.
        acceptFormats:
        - image/*
        uiOrder: 0
        title: Image
        format: string
      score:
        $ref: schema.yaml#/$defs/instill-types/classification/properties/score
        acceptFormats:
        - number
        - integer
      show-score:
        description: Show model confidence score on each instance.
        acceptFormats:
        - boolean
        uiOrder: 0
        title: Show Score
        format: boolean
    required:
    - image
    - category
    - score
    title: Input
    format: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      image:
        description: Output image.
        uiOrder: 0
        title: Image
        format: image/png
    required:
    - image
    title: Output
    format: object
TASK_DRAW_DETECTION:
  shortDescription: Draw detection result on the image.
  input:
    description: Input.
    uiOrder: 0
    properties:
      image:
        description: Input image.
        acceptFormats:
        - image/*
        uiOrder: 0
        title: Image
        format: string
      objects:
        $ref: schema.yaml#/$defs/instill-types/detection/properties/objects
        acceptFormats:
        - array
      show-score:
        description: Show model confidence score on each instance.
        acceptFormats:
        - boolean
        uiOrder: 0
        title: Show Score
        format: boolean
    required:
    - image
    - objects
    title: Input
    format: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      image:
        description: Output image.
        uiOrder: 0
        title: Image
        format: image/png
    required:
    - image
    title: Output
    format: object
TASK_DRAW_KEYPOINT:
  shortDescription: Draw keypoint result on the image.
  input:
    description: Input.
    uiOrder: 0
    properties:
      image:
        description: Input image.
        acceptFormats:
        - image/*
        uiOrder: 0
        title: Image
        format: string
      objects:
        $ref: schema.yaml#/$defs/instill-types/keypoint/properties/objects
        acceptFormats:
        - array
      show-score:
        description: Show model confidence score on each instance.
        acceptFormats:
        - boolean
        uiOrder: 0
        title: Show Score
        format: boolean
    required:
    - image
    - objects
    title: Input
    format: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      image:
        description: Output image.
        uiOrder: 0
        title: Image
        format: image/png
    required:
    - image
    title: Output
    format: object
TASK_DRAW_SEMANTIC_SEGMENTATION:
  shortDescription: Draw semantic segmentation result on the image.
  input:
    description: Input.
    uiOrder: 0
    properties:
      image:
        description: Input image.
        acceptFormats:
        - image/*
        uiOrder: 0
        title: Image
        format: string
      stuffs:
        $ref: schema.yaml#/$defs/instill-types/semantic-segmentation/properties/stuffs
        acceptFormats:
        - array
    required:
    - image
    - stuffs
    title: Input
    format: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      image:
        description: Output image.
        uiOrder: 0
        title: Image
        format: image/png
    required:
    - image
    title: Output
    format: object
TASK_DRAW_INSTANCE_SEGMENTATION:
  shortDescription: Draw instance segmentation result on the image.
  input:
    description: Input.
    uiOrder: 0
    properties:
      image:
        description: Input image.
        acceptFormats:
        - image/*
        uiOrder: 0
        title: Image
        format: string
      objects:
        $ref: schema.yaml#/$defs/instill-types/instance-segmentation/properties/objects
        acceptFormats:
        - array
      show-score:
        description: Show model confidence score on each instance.
        acceptFormats:
        - boolean
        uiOrder: 0
        title: Show Score
        format: boolean
    required:
    - image
    - objects
    title: Input
    format: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      image:
        description: Output image.
        uiOrder: 0
        title: Image
        format: image/png
    required:
    - image
    title: Output
    format: object
TASK_DRAW_OCR:
  shortDescription: Draw OCR result on the image.
  input:
    description: Input.
    uiOrder: 0
    properties:
      image:
        description: Input image.
        acceptFormats:
        - image/*
        uiOrder: 0
        title: Image
        format: string
      objects:
        $ref: schema.yaml#/$defs/instill-types/ocr/properties/objects
        acceptFormats:
        - array
      show-score:
        description: Show model confidence score on each instance.
        acceptFormats:
        - boolean
        uiOrder: 0
        title: Show Score
        format: boolean
    required:
    - image
    - objects
    title: Input
    format: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      image:
        description: Output image.
        uiOrder: 0
        title: Image
        format: image/png
    required:
    - image
    title: Output
    format: object
