import sql from 'k6/x/sql';
import driver from 'k6/x/sql/driver/postgres';

import { uuidv4 } from "https://jslib.k6.io/k6-utils/1.4.0/index.js";
import encoding from "k6/encoding";

let proto;

if (__ENV.API_GATEWAY_PROTOCOL) {
  if (__ENV.API_GATEWAY_PROTOCOL !== "http" && __ENV.API_GATEWAY_PROTOCOL != "https") {
    fail("only allow `http` or `https` for API_GATEWAY_PROTOCOL")
  }
  proto = __ENV.API_GATEWAY_PROTOCOL
} else {
  proto = "http"
}

// API Gateway URL (localhost:8080 from host, api-gateway:8080 from container)
const apiGatewayUrl = __ENV.API_GATEWAY_URL || "localhost:8080";

// Determine if running from host (localhost) or container
export const isHostMode = apiGatewayUrl === "localhost:8080";

// Public hosts (via API Gateway)
export const pipelinePublicHost = `${proto}://${apiGatewayUrl}`;
export const mgmtPublicHost = `${proto}://${apiGatewayUrl}`;
export const pipelineGRPCPublicHost = apiGatewayUrl;
export const mgmtGRPCPublicHost = apiGatewayUrl;

// Private hosts (direct backend, for internal service calls)
// Use localhost ports when running from host, container names when in container
export const pipelinePrivateHost = isHostMode ? `http://localhost:3081` : `http://pipeline-backend:3081`;
export const pipelineGRPCPrivateHost = isHostMode ? `localhost:3081` : `pipeline-backend:3081`;
export const mgmtGRPCPrivateHost = isHostMode ? `localhost:3084` : `mgmt-backend:3084`;

export const dogImg = encoding.b64encode(
  open(`${__ENV.TEST_FOLDER_ABS_PATH}/integration-test/data/dog.jpg`, "b")
);
export const catImg = encoding.b64encode(
  open(`${__ENV.TEST_FOLDER_ABS_PATH}/integration-test/data/cat.jpg`, "b")
);
export const bearImg = encoding.b64encode(
  open(`${__ENV.TEST_FOLDER_ABS_PATH}/integration-test/data/bear.jpg`, "b")
);
export const dogRGBAImg = encoding.b64encode(
  open(`${__ENV.TEST_FOLDER_ABS_PATH}/integration-test/data/dog-rgba.png`, "b")
);

export const namespace = "namespaces/admin"
export const defaultUsername = "admin"
export const defaultPassword = "password"

export const params = {
  headers: {
    "Content-Type": "application/json",
  },
  timeout: "300s",
};

export const paramsGrpc = {
  metadata: {
    "Content-Type": "application/json",
  },
  timeout: "300s",
};

// Invalid Basic Auth credentials for testing unauthorized access
const invalidBasicAuth = encoding.b64encode("invalid-user:invalid-password");

export const paramsGRPCWithInvalidAuth = {
  metadata: {
    "Content-Type": "application/json",
    "Authorization": `Basic ${invalidBasicAuth}`,
  },
};

export const paramsHTTPWithInvalidAuth = {
  headers: {
    "Content-Type": "application/json",
    "Authorization": `Basic ${invalidBasicAuth}`,
  },
};

const yamlRecipe = `
version: v1beta
variable:
  input:
    title: Input
    type: string

output:
  answer:
    title: Answer
    value: \${b01.output.data}

component:
  b01:
    type: base64
    task: TASK_ENCODE
    input:
      data: \${variable.input}
`;

export const simplePipelineWithYAMLRecipe = {
  rawRecipe: yamlRecipe,
  displayName: "Integration Test Pipeline",
  visibility: "VISIBILITY_PRIVATE",
};

export const simplePayload = {
  data: [
    {
      variable: {
        input: "a",
      }
    },
  ],
};

let dbHost = 'localhost';
if (__ENV.DB_HOST) {
  dbHost = __ENV.DB_HOST;
}

// Database connections - pipeline for pipeline data, mgmt for namespace/owner data
export const pipelinedb = sql.open(driver, `postgresql://postgres:password@${dbHost}:5432/pipeline?sslmode=disable`);
export const mgmtDb = sql.open(driver, `postgresql://postgres:password@${dbHost}:5432/mgmt?sslmode=disable`);

// Since the tests rely on a pre-existing user, this prefix is used to clean
// up only the resources generated by these tests.
export const dbIDPrefix = "integration-test-";
