$defs:
  resolution:
    description: Desired number pixels per inch. Defaults to 300. Minimum is 72.
    title: Resolution
    minimum: 72
    default: 300
    format: number
TASK_CONVERT_TO_MARKDOWN:
  shortDescription: Convert document to text in Markdown format.
  input:
    description: Input.
    uiOrder: 0
    properties:
      document:
        description: Base64 encoded PDF/DOCX/DOC/PPTX/PPT/HTML/XLSX/XLS/CSV to be converted to text in Markdown format.
        acceptFormats:
          - '*/*'
        uiOrder: 0
        title: Document
        format: string
      filename:
        description: The name of the file, please remember to add the file extension in the end of file name. e.g. 'example.pdf'.
        acceptFormats:
          - string
        uiOrder: 1
        title: Filename
        format: string
      display-image-tag:
        default: false
        description: Whether to display image tag in the markdown text. Default is 'false'. It is only applicable for convert-2024-08-28 converter. And,
          it is only applicable for the type of PPTX/PPT/DOCX/DOC/PDF.
        uiOrder: 2
        title: Display Image Tag
        format: boolean
      display-all-page-image:
        default: false
        description: Whether to respond the whole page as the images if we detect there could be images in the page. It will only support DOCX/DOC/PPTX/PPT/PDF.
        uiOrder: 3
        title: Display All Page Image
        format: boolean
      resolution:
        $ref: '#/$defs/resolution'
        uiOrder: 4
    required:
      - document
    title: Input
    format: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      body:
        description: Markdown text converted from the PDF document.
        uiOrder: 0
        title: Body
        format: string
      filename:
        description: The name of the file.
        uiOrder: 1
        title: Filename
        format: string
      images:
        description: Images extracted from the document.
        uiOrder: 2
        items:
          format: string
        title: Images
        format: array
      error:
        description: Error message if any during the conversion process.
        uiOrder: 3
        title: Error
        format: string
      all-page-images:
        description: The image contains all the pages in the document if we detect there could be images in the page. It will only support DOCX/DOC/PPTX/PPT/PDF.
        uiOrder: 4
        items:
          format: string
        title: All Page Images
        format: array
      markdowns:
        description: Markdown text converted from the PDF document, separated by page.
        uiOrder: 5
        items:
          format: string
        title: Markdowns
        format: array
    required:
      - body
    title: Output
    format: object
TASK_CONVERT_TO_TEXT:
  shortDescription: Convert document to text.
  input:
    description: Input.
    uiOrder: 0
    properties:
      document:
        description: Base64 encoded PDF/DOC/DOCX/XML/HTML/RTF/MD/PPTX/ODT/TIF/CSV/TXT/PNG document to be converted to plain text.
        acceptFormats:
          - '*/*'
        uiOrder: 0
        title: Document
        format: string
      filename:
        description: The name of the file, please remember to add the file extension in the end of file name. e.g. 'example.pdf'.
        acceptFormats:
          - string
        uiOrder: 1
        title: Filename
        format: string
    required:
      - document
    title: Input
    format: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      body:
        description: Plain text converted from the document.
        uiOrder: 0
        title: Body
        format: string
      error:
        description: Error message if any during the conversion process.
        uiOrder: 3
        title: Error
        format: string
      meta:
        description: Metadata extracted from the document.
        uiOrder: 1
        required: []
        title: Meta
        format: json
      msecs:
        description: Time taken to convert the document.
        uiOrder: 2
        title: Milliseconds
        format: number
      filename:
        description: The name of the file.
        uiOrder: 1
        title: Filename
        format: string
    required:
      - body
      - meta
      - msecs
      - error
    title: Output
    format: object
TASK_CONVERT_TO_IMAGES:
  shortDescription: Convert Document to images.
  input:
    description: Input.
    uiOrder: 0
    properties:
      document:
        description: Base64 encoded PDF/DOCX/DOC/PPT/PPTX to be converted to images.
        acceptFormats:
          - '*/*'
        uiOrder: 0
        title: PDF
        format: string
      filename:
        description: The name of the file, please remember to add the file extension in the end of file name. e.g. 'example.pdf'.
        acceptFormats:
          - string
        uiOrder: 1
        title: Filename
        format: string
      resolution:
        $ref: '#/$defs/resolution'
        uiOrder: 4
    required:
      - document
    title: Input
    format: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      images:
        description: Images converted from the document.
        uiOrder: 0
        items:
          format: string
        title: Images
        format: array
      filenames:
        description: The filenames of the images. The filenames will be appended with the page number. e.g. 'example-1.jpg'.
        uiOrder: 1
        items:
          format: string
        title: Filenames
        format: array
    required:
      - images
    title: Output
    format: object
