$defs:
  search-subject:
    description: Search for emails with a specific subject.
    type: string
    uiOrder: 4
    title: Search Subject
  search-from:
    description: Search for emails from a specific email address.
    type: string
    uiOrder: 2
    title: Search From
  search-to:
    description: Search for emails to a specific email address.
    type: string
    uiOrder: 3
    title: Search To
  limit:
    description: The maximum number of emails to search for.
    type: integer
    uiOrder: 5
    title: Limit
  date:
    description: Search for emails with the date the email was sent.
    type: string
    uiOrder: 6
    title: Search Date
  search-email-message:
    description: Search for emails with a specific message.
    type: string
    uiOrder: 7
    title: Search Message
TASK_SEND_EMAIL:
  shortDescription: Send an email to recipients
  input:
    description: Input.
    uiOrder: 0
    properties:
      recipients:
        description: The email addresses of the recipients.
        type: array
        items:
          type: string
        uiOrder: 2
        title: Recipient
      cc:
        description: The email addresses for Carbon Copy.
        type: array
        items:
          type: string
        uiOrder: 3
        title: Cc
      bcc:
        description: The email addresses for Blind Carbon Copy.
        type: array
        items:
          type: string
        uiOrder: 4
        title: Bcc
      subject:
        description: The subject of the email.
        type: string
        uiOrder: 5
        title: Subject
      message:
        description: The message to be sent.
        type: string
        uiOrder: 6
        title: Message
    required:
      - recipients
      - message
    title: Input
    type: object
  output:
    description: The result of sending the email.
    uiOrder: 0
    properties:
      result:
        description: The result of sending the email.
        uiOrder: 0
        title: Result
        type: string
    required:
      - result
    title: Output
    type: object
TASK_READ_EMAILS:
  shortDescription: Read emails from a mailbox
  input:
    description: Input.
    uiOrder: 0
    properties:
      search:
        description: The search criteria for the emails.
        uiOrder: 0
        properties:
          mailbox:
            description: The mailbox to search for emails.
            type: string
            uiOrder: 1
            title: Mailbox
          search-subject:
            $ref: '#/$defs/search-subject'
          search-from:
            $ref: '#/$defs/search-from'
          search-to:
            $ref: '#/$defs/search-to'
          limit:
            $ref: '#/$defs/limit'
          date:
            $ref: '#/$defs/date'
          search-email-message:
            $ref: '#/$defs/search-email-message'
        required:
          - mailbox
        title: Search
        type: object
    required: []
    title: Input
    type: object
  output:
    description: The emails that match the search criteria.
    uiOrder: 0
    properties:
      emails:
        description: The emails that match the search criteria.
        uiOrder: 0
        items:
          properties:
            date:
              description: The date the email was sent.
              uiOrder: 0
              title: Date
              type: string
            from:
              description: The email address of the sender.
              uiOrder: 1
              title: From
              type: string
            to:
              description: The email addresses of the recipient.
              uiOrder: 2
              items:
                description: The email address of the recipient.
                type: string
              title: To
              type: array
            subject:
              description: The subject of the email.
              uiOrder: 3
              title: Subject
              type: string
            message:
              description: The message of the email.
              uiOrder: 4
              title: Message
              type: string
          required: []
          type: object
        title: Emails
        type: array
    required:
      - emails
    title: Output
    type: object
