$defs:
  search-subject:
    description: Search for emails with a specific subject.
    acceptFormats:
      - string
    uiOrder: 4
    title: Search Subject
    format: string
  search-from:
    description: Search for emails from a specific email address.
    acceptFormats:
      - string
    uiOrder: 2
    title: Search From
    format: string
  search-to:
    description: Search for emails to a specific email address.
    acceptFormats:
      - string
    uiOrder: 3
    title: Search To
    format: string
  limit:
    description: The maximum number of emails to search for.
    acceptFormats:
      - integer
    uiOrder: 5
    title: Limit
    format: integer
  date:
    description: Search for emails with the date the email was sent.
    acceptFormats:
      - string
    uiOrder: 6
    title: Search Date
    format: string
  search-email-message:
    description: Search for emails with a specific message.
    acceptFormats:
      - string
    uiOrder: 7
    title: Search Message
    format: string
TASK_SEND_EMAIL:
  shortDescription: Send an email to recipients
  input:
    description: Input.
    uiOrder: 0
    properties:
      recipients:
        description: The email addresses of the recipients.
        acceptFormats:
          - array
        items:
          format: string
        uiOrder: 2
        title: Recipient
        format: array
      cc:
        description: The email addresses for Carbon Copy.
        acceptFormats:
          - array
        items:
          format: string
        uiOrder: 3
        title: Cc
        format: array
      bcc:
        description: The email addresses for Blind Carbon Copy.
        acceptFormats:
          - array
        items:
          format: string
        uiOrder: 4
        title: Bcc
        format: array
      subject:
        description: The subject of the email.
        acceptFormats:
          - string
        uiOrder: 5
        title: Subject
        format: string
      message:
        description: The message to be sent.
        acceptFormats:
          - string
        uiOrder: 6
        title: Message
        format: string
    required:
      - recipients
      - message
    title: Input
    format: object
  output:
    description: The result of sending the email.
    uiOrder: 0
    properties:
      result:
        description: The result of sending the email.
        uiOrder: 0
        title: Result
        format: string
    required:
      - result
    title: Output
    format: object
TASK_READ_EMAILS:
  shortDescription: Read emails from a mailbox
  input:
    description: Input.
    uiOrder: 0
    properties:
      search:
        description: The search criteria for the emails.
        uiOrder: 0
        properties:
          mailbox:
            description: The mailbox to search for emails.
            acceptFormats:
              - string
            uiOrder: 1
            title: Mailbox
            format: string
          search-subject:
            $ref: '#/$defs/search-subject'
          search-from:
            $ref: '#/$defs/search-from'
          search-to:
            $ref: '#/$defs/search-to'
          limit:
            $ref: '#/$defs/limit'
          date:
            $ref: '#/$defs/date'
          search-email-message:
            $ref: '#/$defs/search-email-message'
        required:
          - mailbox
        title: Search
        format: object
    required: []
    title: Input
    format: object
  output:
    description: The emails that match the search criteria.
    uiOrder: 0
    properties:
      emails:
        description: The emails that match the search criteria.
        uiOrder: 0
        items:
          properties:
            date:
              description: The date the email was sent.
              uiOrder: 0
              title: Date
              format: string
            from:
              description: The email address of the sender.
              uiOrder: 1
              title: From
              format: string
            to:
              description: The email addresses of the recipient.
              uiOrder: 2
              items:
                description: The email address of the recipient.
                format: string
              title: To
              format: array
            subject:
              description: The subject of the email.
              uiOrder: 3
              title: Subject
              format: string
            message:
              description: The message of the email.
              uiOrder: 4
              title: Message
              format: string
          required: []
          format: object
        title: Emails
        format: array
    required:
      - emails
    title: Output
    format: object
