custom: false
documentationUrl: https://www.instill.tech/docs/component/ai/hugging-face
icon: assets/hugging-face.svg
iconUrl: ''
id: hugging-face
public: true
title: Hugging Face
description: Connect the AI models served on the Hugging Face Platform.
tombstone: false
type: COMPONENT_TYPE_AI
uid: 0255ef87-33ce-4f88-b9db-8897f8c17233
vendor: Hugging Face
vendorAttributes: {}
version: 0.1.1
sourceUrl: https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/ai/huggingface/v0
releaseStage: RELEASE_STAGE_ALPHA
