additionalProperties: false
properties:
  api-key:
    description: Fill in your Hugging face API token. To find your token, visit <a href="https://huggingface.co/settings/tokens">here</a>.
    type: string
    instillSecret: true
    uiOrder: 0
    title: API Key
  base-url:
    default: https://api-inference.huggingface.co
    description: Hostname for the endpoint. To use Inference API set to <a href="https://api-inference.huggingface.co">here</a>, for Inference Endpoint
      set to your custom endpoint.
    type: string
    instillSecret: false
    uiOrder: 1
    title: Base URL
  is-custom-endpoint:
    default: false
    description: Fill true if you are using a custom Inference Endpoint and not the Inference API.
    type: boolean
    instillSecret: false
    uiOrder: 2
    title: Is Custom Endpoint
required:
  - api-key
  - base-url
  - is-custom-endpoint
title: Hugging Face Connection
type: object
