documentationUrl: https://www.instill.tech/docs/component/application/github
icon: assets/github.svg
id: github
public: true
title: GitHub
vendor: GitHub
description: Do anything available on GitHub.
tombstone: false
type: COMPONENT_TYPE_APPLICATION
uid: 9c14438b-90fa-41fc-83bb-4a3d9b8cbba6
version: 0.1.0
sourceUrl: https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/application/github/v0
releaseStage: RELEASE_STAGE_ALPHA
