availableTasks:
  - TASK_READ_MESSAGE
  - TASK_WRITE_MESSAGE
availableEvents:
  - EVENT_NEW_MESSAGE
custom: false
documentationUrl: https://docs.instill-ai.com/docs/slack
icon: assets/slack.svg
iconUrl: ""
id: slack
public: true
title: Slack
description: Get and send message on Slack.
tombstone: false
type: COMPONENT_TYPE_APPLICATION
uid: 1e9f469e-da5e-46eb-8a89-23466627e3b5
vendor: Slack
vendorAttributes: {}
version: 0.2.0
sourceUrl: https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/application/slack/v0
releaseStage: RELEASE_STAGE_ALPHA
