$defs:
  user-id:
    description: unique id from Slack.
    uiOrder: 0
    title: User UID
    format: string
  user-name:
    description: user name in Slack.
    uiOrder: 1
    title: User Name
    format: string
TASK_READ_MESSAGE:
  shortDescription: Get the latest message since specific date
  input:
    description: Please input the channel name and the date that we want to start to read.
    uiOrder: 0
    properties:
      channel-name:
        description: Channel name, as displayed on Slack.
        acceptFormats:
          - string
        uiOrder: 0
        title: Channel Name
        format: string
      start-to-read-date:
        description: Date (in `YYYY-MM-DD` format) from which messages will start to be fetched. If not provided, it will be 7 days before the current date.
          The date will be in the UTC timezone.
        acceptFormats:
          - string
        uiOrder: 1
        title: Start to read date
        format: string
    required:
      - channel-name
    title: Input
    format: object
  output:
    description: All messages in Slack channel.
    uiOrder: 0
    properties:
      conversations:
        description: An array of conversations with thread messages.
        uiOrder: 0
        title: Conversations
        items:
          title: conversation details
          properties:
            user-id:
              $ref: '#/$defs/user-id'
            user-name:
              $ref: '#/$defs/user-name'
            message:
              description: message to start a conversation.
              uiOrder: 2
              title: Start Conversation Message
              format: string
            start-date:
              description: when a conversation starts.
              uiOrder: 3
              required: []
              title: Start Date
              format: string
            last-date:
              description: Date of the last message.
              uiOrder: 4
              required: []
              title: Last Date
              format: string
            thread-reply-messages:
              description: replies in a conversation.
              uiOrder: 5
              title: Replied messages
              items:
                title: relied details
                properties:
                  user-id:
                    $ref: '#/$defs/user-id'
                  user-name:
                    $ref: '#/$defs/user-name'
                  datetime:
                    description: replied datetime.
                    uiOrder: 2
                    title: Replied Time
                    format: string
                  message:
                    description: message to reply a conversation.
                    uiOrder: 3
                    title: Replied Message
                    format: string
                required:
                  - user-id
                  - datetime
                  - message
                format: object
              format: array
          required:
            - user-id
            - message
            - start-date
          format: object
        format: array
    required:
      - conversations
    title: Output
    format: object
TASK_WRITE_MESSAGE:
  shortDescription: send message to a specific channel
  title: Send Message
  input:
    description: Input.
    uiOrder: 0
    properties:
      channel-name:
        description: Channel name, as displayed on Slack.
        acceptFormats:
          - string
        uiOrder: 0
        title: Channel Name
        format: string
      message:
        description: The message to be sent to the target channel.
        acceptFormats:
          - string
        uiOrder: 1
        title: Message
        format: string
      as-user:
        default: false
        description: Send the message on behalf of the user identified by the <code>setup.user-token</code> field.
        uiOrder: 2
        title: Send As User
        acceptFormats:
          - boolean
        format: boolean
    required:
      - channel-name
      - message
    title: Input
    format: object
  output:
    description: The greeting sentence.
    uiOrder: 0
    properties:
      result:
        description: Result of the message delivery.
        uiOrder: 0
        required: []
        title: Result
        format: string
    required:
      - result
    title: Output
    format: object
