availableTasks:
  - TASK_CHAT
  - TASK_CACHE
  - TASK_TEXT_EMBEDDINGS
custom: false
icon: assets/gemini.svg
iconUrl: ""
id: gemini
public: true
title: Gemini
description: Connect to Google's Gemini multimodal AI models.
type: COMPONENT_TYPE_AI
uid: 019935a0-8fea-74ee-9829-992f63ae9292
vendor: Google
vendorAttributes: {}
version: 0.1.0
sourceUrl: https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/ai/gemini/v0
releaseStage: RELEASE_STAGE_ALPHA
documentationUrl: https://docs.instill-ai.com/docs/gemini
