additionalProperties: false
properties:
  capture-token:
    description: Fill in your Capture token in the Capture App. To access your tokens, you need a Capture App account and you can sign in with email or
      wallet to acquire the Capture Token.
    type: string
    instillSecret: true
    uiOrder: 0
    title: Capture token
required:
  - capture-token
title: Numbers Protocol Connection
type: object
