TASK_REGISTER:
  shortDescription: Register a file into NumbersProtocol Chain.
  input:
    description: Input.
    uiOrder: 0
    properties:
      images:
        description: The images you want to upload to blockchain.
        acceptFormats:
          - array
        uiOrder: 0
        items:
          contentEncoding: base64
          format: string
        title: Images
        format: array
      headline:
        description: Headline of the asset.
        acceptFormats:
          - string
        uiOrder: 2
        title: Headline
        format: string
      caption:
        description: Caption of the asset.
        acceptFormats:
          - string
        uiOrder: 1
        title: Caption
        format: string
      asset-creator:
        description: Name of the asset creator.
        acceptFormats:
          - string
        uiOrder: 2
        title: Asset Creator
        format: string
      digital-source-type:
        default: trainedAlgorithmicMedia
        description: Specify the type of the source. More details <a href="https://docs.numbersprotocol.io/introduction/numbers-protocol/defining-web3-assets/assettree/digitalsourcetype">here</a>.
        enum:
          - trainedAlgorithmicMedia
          - trainedAlgorithmicData
          - digitalCapture
          - digitalArt
          - algorithmicMedia
        acceptFormats:
          - string
        uiOrder: 5
        title: Digital Source Type
        format: string
      generated-by:
        description: The AI model used to generate the content.
        acceptFormats:
          - string
        uiOrder: 6
        title: Generated By
        format: string
      license:
        description: License.
        uiOrder: 7
        properties:
          document:
            description: URL of the license file.
            acceptFormats:
              - string
            instillEnableCopyButton: true
            uiOrder: 0
            title: License Document
            format: string
          name:
            description: License of the asset file.
            acceptFormats:
              - string
            uiOrder: 1
            title: License Name
            format: string
        required: []
        title: License
        format: object
      mining-preference:
        default: notAllowed
        description: Designates the selection made by the asset creators or licensed owners to decide if the asset is suitable for inclusion in a data mining
          or AI/ML training workflow. More details <a href="https://docs.numbersprotocol.io/introduction/numbers-protocol/defining-web3-assets/assettree/miningpreference">here</a>.
        enum:
          - dataMining
          - aiInference
          - notAllowed
          - aiGenerativeTraining
          - aiGenerativeTrainingWithAuthorship
          - aiTraining
          - aiTrainingWithAuthorship
        acceptFormats:
          - string
        shortDescription: Designates the selection made by the asset creators or licensed owners. More details <a href="https://docs.numbersprotocol.io/introduction/numbers-protocol/defining-web3-assets/assettree/miningpreference">here</a>
        uiOrder: 8
        title: Mining Preference
        format: string
    required:
      - images
    title: Input
    format: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      asset-urls:
        description: Asset Urls.
        instillEnableCopyButton: true
        uiOrder: 0
        items:
          instillEnableCopyButton: true
          title: Asset Url
          format: string
        title: Asset Urls
        format: array
    required:
      - asset-urls
    title: Output
    format: object
