additionalProperties: false
properties:
  endpoint:
    description: >-
      Fill in your Ollama hosting endpoint. ### WARNING ###: As of 2024-07-26, the Ollama component does not support authentication methods.
      To prevent unauthorized access to your Ollama serving resources, please implement additional security measures such as IP whitelisting.
    type: string
    default: http://localhost:11434
    uiOrder: 0
    title: Endpoint
  auto-pull:
    description: Automatically pull the requested models from the Ollama server if the model is not found in the local cache.
    type: boolean
    uiOrder: 1
    title: Model Auto-Pull
required:
  - endpoint
  - auto-pull
title: Ollama Connection
type: object
