BEGIN;

DROP INDEX IF EXISTS component_definition_index_filter;

DROP TABLE IF EXISTS component_definition_index CASCADE;

DROP TYPE IF EXISTS VALID_RELEASE_STAGE;

DROP TYPE IF EXISTS COMPONENT_DEFINITION_VALID_COMPONENT_TYPE ;

COMMIT;
