BEGIN;

ALTER TYPE COMPONENT_DEFINITION_VALID_COMPONENT_TYPE RENAME VALUE 'COMPONENT_TYPE_AI' TO 'COMPONENT_TYPE_CONNECTOR_AI';
ALTER TYPE COMPONENT_DEFINITION_VALID_COMPONENT_TYPE RENAME VALUE 'COMPONENT_TYPE_DATA' TO 'COMPONENT_TYPE_CONNECTOR_DATA';
ALTER TYPE COMPONENT_DEFINITION_VALID_COMPONENT_TYPE RENAME VALUE 'COMPONENT_TYPE_APPLICATION' TO 'COMPONENT_TYPE_CONNECTOR_APPLICATION';

ALTER TABLE public.pipeline DROP COLUMN number_of_runs;
ALTER TABLE public.pipeline DROP COLUMN last_run_time;
DROP INDEX IF EXISTS pipeline_number_of_runs;
DROP INDEX IF EXISTS pipeline_last_run_time;

COMMIT;
