BEGIN;
ALTER TYPE COMPONENT_DEFINITION_VALID_COMPONENT_TYPE ADD VALUE 'COMPONENT_TYPE_GENERIC';
COMMIT;

BEGIN;
UPDATE public.component_definition_index SET component_type='COMPONENT_TYPE_GENERIC' WHERE id='restapi';
COMMIT;
