BEGIN;

ALTER TYPE COMPONENT_DEFINITION_VALID_COMPONENT_TYPE RENAME VALUE 'COMPONENT_TYPE_CONNECTOR_AI' TO 'COMPONENT_TYPE_AI';
ALTER TYPE COMPONENT_DEFINITION_VALID_COMPONENT_TYPE RENAME VALUE 'COMPONENT_TYPE_CONNECTOR_DATA' TO 'COMPONENT_TYPE_DATA';
ALTER TYPE COMPONENT_DEFINITION_VALID_COMPONENT_TYPE RENAME VALUE 'COMPONENT_TYPE_CONNECTOR_APPLICATION' TO 'COMPONENT_TYPE_APPLICATION';

ALTER TABLE public.pipeline ADD COLUMN number_of_runs INTEGER DEFAULT 0;
ALTER TABLE public.pipeline ADD COLUMN last_run_time TIMESTAMPTZ DEFAULT '0001-01-01T00:00:00Z';
CREATE INDEX pipeline_number_of_runs ON public.pipeline (number_of_runs);
CREATE INDEX pipeline_last_run_time ON public.pipeline (last_run_time);

COMMIT;
