$defs:
  def-input:
    phone-number-id:
      description: >-
        Phone Number ID. Obtainable through the app dashboard. Note: This is for sender.
      type: string
      uiOrder: 0
      title: Phone Number ID
    to:
      description: The number of the recipient you are sending the message to.
      type: string
      uiOrder: 1
      title: Recipient Phone Number
    template:
      name:
        description: Name of the template.
        type: string
        title: Template Name
      language-code:
        description: The code of the language in which the template is used. [Supported languages](https://developers.facebook.com/docs/whatsapp/api/messages/message-templates#supported-languages).
        type: string
        title: Language Code
      body-parameters:
        description: Specify the parameters for the body section of the template. Leave this blank if there is no parameter.
        title: Body Parameters
        items:
          title: Body Parameter
          description: Body parameter.
          type: string
        type: array
      button-parameters:
        description: >-
          Specify the parameters for button(s). Leave this blank if there is no parameter. Follow this format or it won't work: button_index;button_type;value_of_the_parameter.
          The separator is a semicolon. button_index starts at 0. Example: 0;quick_reply;randomvalue. Note: This button parameter only support three types
          `quick_reply`, `url` and `copy_code`."
        title: Button Parameters
        items:
          title: Button Parameter
          description: Button parameter.
          type: string
        type: array
    media:
      id-or-link:
        description: Input either ID or link of the media. If the input has `http`, it will be considered as a link.
        type: string
      caption:
        description: >-
          Media asset caption. Description of the media. This property cannot be used when the media type is audio. If audio tried to use this
          property, it will be ignored.
        type: string
      filename:
        description: >-
          The filename of the document. Only document can use this property. This property will specify what format the document is displayed
          as in WhatsApp. If other media type tried to use this property, it will be ignored.
        type: string
    location:
      latitude:
        description: Location latitude.
        type: number
      longitude:
        description: Location longitude.
        type: number
      location-name:
        description: Name of the location.
        type: string
      address:
        description: Address of the location.
        type: string
  def-output:
    recipient-wa-id:
      description: The WhatsApp ID of the recipient. Most likely the same with their phone number.
      uiOrder: 0
      title: Recipient WhatsApp ID
      type: string
    message-id:
      description: The ID of the message.
      uiOrder: 1
      title: Message ID
      type: string
    message-status:
      description: The status of the message.
      uiOrder: 2
      title: Message Status
      type: string
TASK_SEND_TEXT_BASED_TEMPLATE_MESSAGE:
  shortDescription: Send text-based template message. This task support header(text), body and button parameters.
  input:
    description: Template information.
    uiOrder: 0
    properties:
      phone-number-id:
        $ref: "#/$defs/def-input/phone-number-id"
      to:
        $ref: "#/$defs/def-input/to"
      name:
        $ref: "#/$defs/def-input/template/name"
        uiOrder: 2
      language-code:
        $ref: "#/$defs/def-input/template/language-code"
        uiOrder: 3
      header-parameters:
        description: Specify the parameters for the header section of the template. Leave this blank if there is no parameter.
        uiOrder: 4
        title: Header Parameters
        items:
          title: Header Parameter
          description: Header parameter.
          type: string
        type: array
      body-parameters:
        $ref: "#/$defs/def-input/template/body-parameters"
        uiOrder: 5
      button-parameters:
        $ref: "#/$defs/def-input/template/button-parameters"
        uiOrder: 6
    required:
      - phone-number-id
      - to
      - name
      - language-code
    title: Input
    type: object
  output:
    description: API response.
    uiOrder: 0
    properties:
      recipient-wa-id:
        $ref: "#/$defs/def-output/recipient-wa-id"
      message-id:
        $ref: "#/$defs/def-output/message-id"
      message-status:
        $ref: "#/$defs/def-output/message-status"
    required:
      - recipient-wa-id
      - message-id
      - message-status
    title: Output
    type: object
TASK_SEND_MEDIA_BASED_TEMPLATE_MESSAGE:
  shortDescription: Send media-based template message. This task support header(image, document & video), body and button parameters.
  input:
    description: Template information.
    uiOrder: 0
    properties:
      phone-number-id:
        $ref: "#/$defs/def-input/phone-number-id"
      to:
        $ref: "#/$defs/def-input/to"
      name:
        $ref: "#/$defs/def-input/template/name"
        uiOrder: 2
      language-code:
        $ref: "#/$defs/def-input/template/language-code"
        uiOrder: 3
      media-type:
        enum:
          - image
          - video
          - document
        example: none
        description: Specify the header(media) type for the header section of the template.
        type: string
        uiOrder: 4
        title: Header Type
      id-or-link:
        title: ID Or Link (Header Parameter)
        $ref: "#/$defs/def-input/media/id-or-link"
        uiOrder: 5
      filename:
        title: Filename (Header Parameter)
        $ref: "#/$defs/def-input/media/filename"
        uiOrder: 6
      body-parameters:
        $ref: "#/$defs/def-input/template/body-parameters"
        uiOrder: 7
      button-parameters:
        $ref: "#/$defs/def-input/template/button-parameters"
        uiOrder: 8
    required:
      - phone-number-id
      - to
      - name
      - language-code
      - media-type
      - id-or-link
    title: Input
    type: object
  output:
    description: API response.
    uiOrder: 0
    properties:
      recipient-wa-id:
        $ref: "#/$defs/def-output/recipient-wa-id"
      message-id:
        $ref: "#/$defs/def-output/message-id"
      message-status:
        $ref: "#/$defs/def-output/message-status"
    required:
      - recipient-wa-id
      - message-id
      - message-status
    title: Output
    type: object
TASK_SEND_LOCATION_BASED_TEMPLATE_MESSAGE:
  shortDescription: Send location-based template message. This task support header(location), body and button parameters.
  input:
    description: Template information.
    uiOrder: 0
    properties:
      phone-number-id:
        $ref: "#/$defs/def-input/phone-number-id"
      to:
        $ref: "#/$defs/def-input/to"
      name:
        $ref: "#/$defs/def-input/template/name"
        uiOrder: 2
      language-code:
        $ref: "#/$defs/def-input/template/language-code"
        uiOrder: 3
      latitude:
        title: Latitude (Header Parameter)
        $ref: "#/$defs/def-input/location/latitude"
        uiOrder: 4
      longitude:
        title: Longitude (Header Parameter)
        $ref: "#/$defs/def-input/location/longitude"
        uiOrder: 5
      location-name:
        title: Location Name (Header Parameter)
        $ref: "#/$defs/def-input/location/location-name"
        uiOrder: 6
      address:
        title: Location Address (Header Parameter)
        $ref: "#/$defs/def-input/location/address"
        uiOrder: 7
      body-parameters:
        $ref: "#/$defs/def-input/template/body-parameters"
        uiOrder: 8
      button-parameters:
        $ref: "#/$defs/def-input/template/button-parameters"
        uiOrder: 9
    required:
      - phone-number-id
      - to
      - name
      - language-code
      - latitude
      - longitude
      - location-name
      - address
    title: Input
    type: object
  output:
    description: API response.
    uiOrder: 0
    properties:
      recipient-wa-id:
        $ref: "#/$defs/def-output/recipient-wa-id"
      message-id:
        $ref: "#/$defs/def-output/message-id"
      message-status:
        $ref: "#/$defs/def-output/message-status"
    required:
      - recipient-wa-id
      - message-id
      - message-status
    title: Output
    type: object
TASK_SEND_AUTHENTICATION_TEMPLATE_MESSAGE:
  shortDescription:
    Send authentication template message with one-time password button (The button is used to copy the password to clipboard). Authentication
    template has no header parameters.
  input:
    description: Template information.
    uiOrder: 0
    properties:
      phone-number-id:
        $ref: "#/$defs/def-input/phone-number-id"
      to:
        $ref: "#/$defs/def-input/to"
      name:
        $ref: "#/$defs/def-input/template/name"
        uiOrder: 2
      language-code:
        $ref: "#/$defs/def-input/template/language-code"
        uiOrder: 3
      one-time-password:
        description: One-time password to be sent to the recipient. Maximum 15 characters.
        type: string
        uiOrder: 4
        title: One-Time Password
    required:
      - phone-number-id
      - to
      - name
      - language-code
      - one-time-password
    title: Input
    type: object
  output:
    description: API response.
    uiOrder: 0
    properties:
      recipient-wa-id:
        $ref: "#/$defs/def-output/recipient-wa-id"
      message-id:
        $ref: "#/$defs/def-output/message-id"
      message-status:
        $ref: "#/$defs/def-output/message-status"
    required:
      - recipient-wa-id
      - message-id
      - message-status
    title: Output
    type: object
TASK_SEND_TEXT_MESSAGE:
  shortDescription: >-
    Send text message. Note: Message can only be sent when the 24-hour customer service window is open. For more information, please visit
    [here](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-messages#customer-service-windows)
  input:
    description: Text input.
    uiOrder: 0
    properties:
      phone-number-id:
        $ref: "#/$defs/def-input/phone-number-id"
      to:
        $ref: "#/$defs/def-input/to"
      body:
        description: Body of the message.
        type: string
        uiOrder: 2
        title: Text
      preview-url:
        enum:
          - "false"
          - "true"
        example: "false"
        description: Specify whether URL should be previewed or not. This will have no affect if the message does not contain any URL.
        type: string
        uiOrder: 3
        title: Preview URL
    required:
      - phone-number-id
      - to
      - body
      - preview-url
    title: Input
    type: object
  output:
    description: API response.
    uiOrder: 0
    properties:
      recipient-wa-id:
        $ref: "#/$defs/def-output/recipient-wa-id"
      message-id:
        $ref: "#/$defs/def-output/message-id"
    required:
      - recipient-wa-id
      - message-id
    title: Output
    type: object
TASK_SEND_MEDIA_MESSAGE:
  shortDescription: >-
    Send media message. Media supported: video, audio, document, image. Note: Message can only be sent when the 24-hour customer service
    window is open. For more information, please visit [here](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-messages#customer-service-windows).
  input:
    description: Media input.
    uiOrder: 0
    properties:
      phone-number-id:
        $ref: "#/$defs/def-input/phone-number-id"
      to:
        $ref: "#/$defs/def-input/to"
      media-type:
        enum:
          - image
          - audio
          - document
          - video
        example: image
        description: Specify what media to send.
        type: string
        uiOrder: 2
        title: Media Type
      id-or-link:
        title: ID Or Link
        $ref: "#/$defs/def-input/media/id-or-link"
        uiOrder: 3
      caption:
        title: Caption
        $ref: "#/$defs/def-input/media/caption"
        uiOrder: 4
      filename:
        title: Filename
        $ref: "#/$defs/def-input/media/filename"
        uiOrder: 5
    required:
      - phone-number-id
      - to
      - media-type
      - id-or-link
    title: Input
    type: object
  output:
    description: API response.
    uiOrder: 0
    properties:
      recipient-wa-id:
        $ref: "#/$defs/def-output/recipient-wa-id"
      message-id:
        $ref: "#/$defs/def-output/message-id"
    required:
      - recipient-wa-id
      - message-id
    title: Output
    type: object
TASK_SEND_LOCATION_MESSAGE:
  shortDescription:
    "Send location message. Note: Message can only be sent when the 24-hour customer service window is open. For more information, please
    visit [here](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-messages#customer-service-windows)"
  input:
    description: Location input.
    uiOrder: 0
    properties:
      phone-number-id:
        $ref: "#/$defs/def-input/phone-number-id"
      to:
        $ref: "#/$defs/def-input/to"
      latitude:
        title: Latitude
        $ref: "#/$defs/def-input/location/latitude"
        uiOrder: 2
      longitude:
        title: Longitude
        $ref: "#/$defs/def-input/location/longitude"
        uiOrder: 3
      location-name:
        title: Location Name
        $ref: "#/$defs/def-input/location/location-name"
        uiOrder: 4
      address:
        title: Location Address
        $ref: "#/$defs/def-input/location/address"
        uiOrder: 5
    required:
      - phone-number-id
      - to
      - latitude
      - longitude
      - location-name
      - address
    title: Input
    type: object
  output:
    description: API response.
    uiOrder: 0
    properties:
      recipient-wa-id:
        $ref: "#/$defs/def-output/recipient-wa-id"
      message-id:
        $ref: "#/$defs/def-output/message-id"
    required:
      - recipient-wa-id
      - message-id
    title: Output
    type: object
TASK_SEND_CONTACT_MESSAGE:
  shortDescription: >-
    Send contact message. Note: Message can only be sent when the 24-hour customer service window is open. For more information, please
    visit [here](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-messages#customer-service-windows).
  input:
    description: Contact input.
    uiOrder: 0
    properties:
      phone-number-id:
        $ref: "#/$defs/def-input/phone-number-id"
      to:
        $ref: "#/$defs/def-input/to"
      first-name:
        description: First name of the contact.
        type: string
        uiOrder: 2
        title: First Name
      middle-name:
        description: Middle name of the contact.
        type: string
        uiOrder: 3
        title: Middle Name
      last-name:
        description: Last name of the contact.
        type: string
        uiOrder: 4
        title: Last Name
      phone-number:
        description: Phone number of the contact.
        type: string
        uiOrder: 5
        title: Phone Number
      phone-number-type:
        enum:
          - none
          - CELL
          - MAIN
          - PHONE
          - HOME
          - WORK
        example: none
        description: Phone number type of the contact. If there is no phone number, pick none.
        type: string
        uiOrder: 6
        title: Phone Number Type
      email:
        description: Email of the contact.
        type: string
        uiOrder: 7
        title: Email
      email-type:
        enum:
          - none
          - HOME
          - WORK
        example: none
        description: Email type of the contact. If there is no email, pick none.
        type: string
        uiOrder: 8
        title: Email Type
      birthday:
        description: Birthday of the contact. Format is in `YYYY-MM-DD`.
        type: string
        uiOrder: 9
        title: Birthday
    required:
      - phone-number-id
      - to
      - first-name
    title: Input
    type: object
  output:
    description: API response.
    uiOrder: 0
    properties:
      recipient-wa-id:
        $ref: "#/$defs/def-output/recipient-wa-id"
      message-id:
        $ref: "#/$defs/def-output/message-id"
    required:
      - recipient-wa-id
      - message-id
    title: Output
    type: object
TASK_SEND_INTERACTIVE_CALL_TO_ACTION_URL_BUTTON_MESSAGE:
  shortDescription: >-
    Send interactive Call-To-Action URL button message. Note: Message can only be sent when the 24-hour customer service window is open.
    For more information, please visit [here](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-messages#customer-service-windows).
  input:
    description: Interactive CTA URL button input.
    uiOrder: 0
    properties:
      phone-number-id:
        $ref: "#/$defs/def-input/phone-number-id"
      to:
        $ref: "#/$defs/def-input/to"
      header-text:
        description: Message header text.
        type: string
        uiOrder: 2
        title: Header Text
      body-text:
        description: Message body text.
        type: string
        uiOrder: 3
        title: Body Text
      footer-text:
        description: Message footer text.
        type: string
        uiOrder: 4
        title: Footer Text
      button-display-text:
        description: The text displayed on the button.
        type: string
        uiOrder: 5
        title: Button Display Text
      button-url:
        description: URL to load when the user tapped the button.
        type: string
        uiOrder: 6
        title: Button URL
    required:
      - phone-number-id
      - to
      - body-text
      - button-display-text
      - button-url
    title: Input
    type: object
  output:
    description: API response.
    uiOrder: 0
    properties:
      recipient-wa-id:
        $ref: "#/$defs/def-output/recipient-wa-id"
      message-id:
        $ref: "#/$defs/def-output/message-id"
    required:
      - recipient-wa-id
      - message-id
    title: Output
    type: object
