additionalProperties: false
properties:
  api-key:
    description: Fill in your Freshdesk API key. To find your key, go to profile settigs and on the right pane, you can get your key once you have completed
      the captcha verification.
    acceptFormats:
      - string
    instillSecret: true
    uiOrder: 0
    title: API key
    format: string
  domain:
    description: Your Freshdesk domain. You can find this by going to Admin -> Search for "Portals" -> Portal URL. Your portal URL will look like "yourdomain.freshdesk.com".
      Please only input your domain and not the whole URL.
    acceptFormats:
      - string
    instillSecret: true
    uiOrder: 1
    title: Domain
    format: string
required:
  - api-key
  - domain
title: Freshdesk Connection
format: object
