additionalProperties: false
properties:
  token:
    description: Fill in your Jira API token. You can generate one from your Jira account "settings > security > API tokens".
    type: string
    instillSecret: true
    uiOrder: 0
    title: Token
  email:
    description: Fill in your Jira email address.
    type: string
    uiOrder: 1
    title: Email
  base-url:
    description: Fill in your Jira base URL. For example, if your Jira URL is "https://mycompany.atlassian.net/...", then your base URL is https://mycompany.atlassian.net.
    type: string
    uiOrder: 1
    title: Base URL
required:
  - token
  - email
  - base-url
title: Jira Connection
type: object
