additionalProperties: false
properties:
  api-key:
    description: Fill in your Cohere API key. To find your keys, visit the Cohere dashboard page.
    type: string
    instillSecret: true
    instillCredential: true
    uiOrder: 0
    title: API Key
required: []
title: Cohere Connection
type: object
