$defs:
  multi-modal-content:
    items:
      properties:
        image-url:
          properties:
            url:
              description: Either a URL of the image or the base64 encoded image data.
              title: URL
              uiOrder: 0
              format: string
          required:
          - url
          title: Image URL
          description: The image URL.
          uiOrder: 0
          format: object
        text:
          description: The text content.
          title: Text
          uiOrder: 1
          format: string
        type:
          description: The type of the content part.
          enum:
          - text
          - image_url
          title: Type
          uiOrder: 2
          format: string
      required:
      - type
      format: object
    format: array
  chat-message:
    properties:
      content:
        $ref: '#/$defs/multi-modal-content'
        description: The message content.
        uiOrder: 1
        title: Content
      role:
        description: The message role, i.e. 'system', 'user' or 'assistant'.
        uiOrder: 0
        title: Role
        format: string
    required:
    - role
    - content
    title: Chat Message
    format: object
  common:
    description: Input.
    uiOrder: 0
    properties:
      image-base64:
        description: Image base64.
        acceptFormats:
        - image/*
        uiOrder: 2
        title: Image
        format: string
      model-name:
        description: The Instill Model model to be used.
        acceptFormats:
        - string
        uiOrder: 0
        title: Model Name
        format: string
    required:
    - image-base64
    - model-name
    title: Input
    format: object
  citation:
    properties:
      start:
        description: The start position of the citation.
        acceptFormats:
        - integer
        uiOrder: 0
        title: Start
        format: integer
      end:
        description: The end position of the citation.
        acceptFormats:
        - integer
        uiOrder: 1
        title: End
        format: integer
      text:
        description: The text body of the citation.
        acceptFormats:
        - string
        uiOrder: 2
        title: Text
        format: string
    required:
    - start
    - end
    - text
    title: Citation
    format: object
  command-usage:
    description: Token Usage on the Cohere Platform Command Models.
    uiOrder: 1
    properties:
      input-tokens:
        description: The input tokens used by Cohere Models.
        uiOrder: 2
        title: Input Tokens
        format: number
      output-tokens:
        description: The output tokens generated by Cohere Models.
        uiOrder: 3
        title: Output Tokens
        format: number
    required:
    - input-tokens
    - output-tokens
    title: Usage
    format: object
  rerank-usage:
    description: Search Usage on the Cohere Platform Rerank Models.
    uiOrder: 1
    properties:
      search-counts:
        description: The search count used by Cohere Models.
        uiOrder: 1
        title: Search Counts
        format: number
    required:
    - search-counts
    title: Usage
    format: object
  embed-usage:
    description: Token usage on the Cohere platform embed models.
    uiOrder: 1
    properties:
      tokens:
        description: The token count used by Cohere Models.
        uiOrder: 1
        title: Token Count
        format: number
    required:
    - tokens
    title: Usage
    format: object
TASK_TEXT_GENERATION_CHAT:
  shortDescription: Provide text outputs in response to text inputs.
  description: Cohere's text generation models (often called generative pre-trained
    transformers or large language models) have been trained to understand natural
    language, code, and images. The models provide text outputs in response to their
    inputs. The inputs to these models are also referred to as "prompts". Designing
    a prompt is essentially how you “program” a large language model model, usually
    by providing instructions or some examples of how to successfully complete a task.
  input:
    description: Input.
    uiOrder: 0
    properties:
      chat-history:
        description: 'Incorporate external chat history, specifically previous messages
          within the conversation. Each message should adhere to the format: : {"role":
          "The message role, i.e. ''USER'' or ''CHATBOT''", "content": "message content"}.'
        acceptFormats:
        - object
        shortDescription: 'Incorporate external chat history, specifically previous
          messages within the conversation. (Note: As for 2024-06-24 Cohere models
          are not multimodal, so images will be ignored.)'
        uiOrder: 4
        items:
          $ref: '#/$defs/chat-message'
        title: Chat history
        format: array
      max-new-tokens:
        default: 50
        description: The maximum number of tokens for model to generate (default=50).
        acceptFormats:
        - integer
        uiOrder: 6
        title: Max New Tokens
        format: integer
      model-name:
        enum:
        - command-r-plus
        - command-r
        - command
        - command-nightly
        - command-light
        - command-light-nightly
        example: command-r-plus
        description: The Cohere command model to be used.
        acceptFormats:
        - string
        instillCredentialMap:
          values:
          - command-r-plus
          - command-r
          - command
          - command-light
          targets:
          - setup.api-key
        uiOrder: 0
        title: Model Name
        format: string
      prompt:
        description: The prompt text.
        acceptFormats:
        - string
        uiOrder: 2
        title: Prompt
        format: string
      prompt-images:
        description: 'The prompt images (Note: As for 2024-06-24 Cohere models are
          not multimodal, so images will be ignored.).'
        acceptFormats:
        - array
        uiOrder: 3
        items:
          format: string
        title: Prompt Images
        format: array
      seed:
        default: 42
        description: The seed (default=42).
        acceptFormats:
        - integer
        uiOrder: 4
        title: Seed
        format: integer
      system-message:
        default: You are a helpful assistant.
        description: The system message helps set the behavior of the assistant. For
          example, you can modify the personality of the assistant or provide specific
          instructions about how it should behave throughout the conversation. By
          default, the model’s behavior is using a generic message as "You are a helpful
          assistant.".
        acceptFormats:
        - string
        shortDescription: The system message helps set the behavior of the assistant
        uiOrder: 2
        title: System Message
        format: string
      temperature:
        default: 0.7
        description: The temperature for sampling (default=0.7).
        acceptFormats:
        - number
        uiOrder: 5
        title: Temperature
        format: number
      top-k:
        default: 10
        description: Top k for sampling (default=10).
        acceptFormats:
        - integer
        uiOrder: 5
        title: Top K
        format: integer
      documents:
        description: The documents to be used for the model, for optimal performance,
          the length of each document should be less than 300 words.
        acceptFormats:
        - array
        uiOrder: 3
        items:
          format: string
        title: Documents
        format: array
    required:
    - prompt
    - model-name
    title: Input
    format: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      text:
        description: Model Output.
        uiOrder: 0
        title: Text
        format: string
      citations:
        description: Citations.
        uiOrder: 1
        acceptFormats:
        - array
        title: Citations
        items:
          $ref: '#/$defs/citation'
        format: array
      usage:
        $ref: '#/$defs/command-usage'
        uiOrder: 2
    required:
    - text
    title: Output
    format: object
TASK_TEXT_EMBEDDINGS:
  shortDescription: Turn text into a vector of numbers that capture its meaning, unlocking
    use cases like semantic search.
  description: An embedding is a list of floating point numbers that captures semantic
    information about the text that it represents.
  input:
    uiOrder: 0
    properties:
      model-name:
        enum:
        - embed-english-v3.0
        - embed-multilingual-v3.0
        - embed-english-light-v3.0
        - embed-multilingual-light-v3.0
        example: embed-multilingual-v3.0
        description: The Cohere embed model to be used.
        acceptFormats:
        - string
        instillCredentialMap:
          values:
          - embed-english-v3.0
          - embed-multilingual-v3.0
          - embed-english-light-v3.0
          - embed-multilingual-light-v3.0
          targets:
          - setup.api-key
        uiOrder: 0
        title: Model Name
        format: string
      text:
        description: The text.
        acceptFormats:
        - string
        uiOrder: 1
        title: Text
        format: string
      input-type:
        enum:
        - search_document
        - search_query
        - classification
        - clustering
        example: search_document
        description: Specifies the type of input passed to the model.
        acceptFormats:
        - string
        uiOrder: 0
        title: Input Type
        format: string
      embedding-type:
        enum:
        - float
        - int8
        - uint8
        - binary
        - ubinary
        example: float
        description: Specifies the return type of embedding, Note that 'binary'/'ubinary'
          options means the component will return packed unsigned binary embeddings.
          The length of each binary embedding is 1/8 the length of the float embeddings
          of the provided model.
        acceptFormats:
        - string
        uiOrder: 0
        title: Embedding Type
        format: string
    required:
    - text
    - model-name
    - input-type
    - embedding-type
    title: Input
    format: object
  output:
    uiOrder: 0
    properties:
      embedding:
        items:
          title: Embedding
          format: number
        description: Embedding of the input text.
        uiOrder: 0
        title: Embedding
        format: array
      usage:
        $ref: '#/$defs/embed-usage'
    required:
    - embedding
    title: Output
    format: object
TASK_TEXT_RERANKING:
  shortDescription: Sort text inputs by semantic relevance to a specified query.
  description: Rerank models sort text inputs by semantic relevance to a specified
    query. They are often used to sort search results returned from an existing search
    solution.
  input:
    uiOrder: 0
    properties:
      model-name:
        enum:
        - rerank-english-v3.0
        - rerank-multilingual-v3.0
        example: rerank-multilingual-v3.0
        description: The Cohere rerank model to be used.
        acceptFormats:
        - string
        instillCredentialMap:
          values:
          - rerank-english-v3.0
          - rerank-multilingual-v3.0
          targets:
          - setup.api-key
        uiOrder: 0
        title: Model Name
        format: string
      query:
        description: The query.
        acceptFormats:
        - string
        uiOrder: 1
        title: Query
        format: string
      documents:
        description: The documents to be used for reranking.
        acceptFormats:
        - array
        uiOrder: 2
        items:
          format: string
        title: Documents
        format: array
      top-n:
        default: 3
        description: The number of most relevant documents or indices to return. Defaults
          to the length of the documents (default=3).
        acceptFormats:
        - integer
        uiOrder: 3
        title: Top N
        format: integer
      max-chunks-per-doc:
        default: 10
        description: The maximum number of chunks to produce internally from a document
          (default=10).
        acceptFormats:
        - integer
        uiOrder: 4
        title: Maximum number of chunks per document
        format: integer
    required:
    - query
    - model-name
    - documents
    title: Input
    format: object
  output:
    uiOrder: 0
    properties:
      ranking:
        items:
          title: Documents
          format: string
        description: Reranked documents.
        uiOrder: 0
        title: Reranked documents
        format: array
      usage:
        $ref: '#/$defs/rerank-usage'
      relevance:
        items:
          title: Relevance
          format: number
        description: The relevance scores of the reranked documents.
        uiOrder: 0
        title: Reranked documents relevance
        format: array
    required:
    - ranking
    title: Output
    format: object
