$defs:
  result:
    properties:
      link:
        description: The full URL to which the search result is pointing, e.g., http://www.example.com/foo/bar.
        acceptFormats:
        - string
        uiOrder: 1
        title: Link
        format: string
      link-html:
        description: The scraped raw html of the link associated with this search
          result.
        acceptFormats:
        - string
        uiOrder: 4
        title: Link HTML
        format: string
      link-text:
        description: The scraped text of the link associated with this search result,
          in plain text.
        acceptFormats:
        - string
        uiOrder: 3
        title: Link Text
        format: string
      snippet:
        description: The snippet from the page associated with this search result,
          in plain text.
        acceptFormats:
        - string
        uiOrder: 2
        title: Snippet
        format: string
      title:
        description: The title of a search result, in plain text.
        acceptFormats:
        - string
        uiOrder: 0
        title: Title
        format: string
    required:
    - title
    - link
    - snippet
    title: Result
    format: object
TASK_SEARCH:
  shortDescription: Search data via Google Search Engine.
  input:
    uiOrder: 0
    properties:
      include-link-html:
        default: false
        description: Indicate whether to scrape the link and include the raw HTML
          of the link associated with this search result in the 'link-html' field.
        acceptFormats:
        - boolean
        uiOrder: 3
        title: Include Link HTML
        format: boolean
      include-link-text:
        default: false
        description: Indicate whether to scrape the link and include the text of the
          link associated with this search result in the 'link-text' field.
        acceptFormats:
        - boolean
        uiOrder: 2
        title: Include Link Text
        format: boolean
      query:
        description: The search query for Google.
        acceptFormats:
        - string
        uiOrder: 0
        title: Query
        format: string
      top-k:
        default: 10
        description: The number of results to return for each query.
        acceptFormats:
        - integer
        uiOrder: 1
        maximum: 100
        minimum: 1
        title: Top K
        format: integer
    required:
    - query
    title: Input
    format: object
  output:
    uiOrder: 0
    properties:
      results:
        description: The returned search results from Google.
        uiOrder: 0
        items:
          $ref: '#/$defs/result'
        title: Results
        format: array
    required:
    - results
    title: Output
    format: object
