server:
  port: 8080
  https:
    cert:   # /ssl/tls.crt
    key:    # /ssl/tls.key
  corsorigins:
    - http://localhost
    - https://instill-inc.tech
    - https://instill.tech
  paginate:
    salt: 3PTkdu4FRvmSezf2
database:
  username: postgres
  password: password
  host: localhost
  port: 5432
  name: pipeline
  version: 6
  timezone: Etc/UTC
  pool:
    idleconnections: 5
    maxconnections: 10
    connlifetime: 30 # In minutes
cache:
  redis:
    redisoptions:
      addr: localhost:6379
temporal:
  clientoptions:
    namespace: pipeline
    hostport: localhost:7233
modelbackend:
  tls: false
  host: localhost
  port: 8081
