// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/instill-ai/protogen-go/vdp/model/v1alpha (interfaces: ModelServiceClient)

// Package service_test is a generated GoMock package.
package service_test

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	modelv1alpha "github.com/instill-ai/protogen-go/vdp/model/v1alpha"
	grpc "google.golang.org/grpc"
)

// MockModelServiceClient is a mock of ModelServiceClient interface.
type MockModelServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockModelServiceClientMockRecorder
}

// MockModelServiceClientMockRecorder is the mock recorder for MockModelServiceClient.
type MockModelServiceClientMockRecorder struct {
	mock *MockModelServiceClient
}

// NewMockModelServiceClient creates a new mock instance.
func NewMockModelServiceClient(ctrl *gomock.Controller) *MockModelServiceClient {
	mock := &MockModelServiceClient{ctrl: ctrl}
	mock.recorder = &MockModelServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelServiceClient) EXPECT() *MockModelServiceClientMockRecorder {
	return m.recorder
}

// CancelModelOperation mocks base method.
func (m *MockModelServiceClient) CancelModelOperation(arg0 context.Context, arg1 *modelv1alpha.CancelModelOperationRequest, arg2 ...grpc.CallOption) (*modelv1alpha.CancelModelOperationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelModelOperation", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.CancelModelOperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelModelOperation indicates an expected call of CancelModelOperation.
func (mr *MockModelServiceClientMockRecorder) CancelModelOperation(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelModelOperation", reflect.TypeOf((*MockModelServiceClient)(nil).CancelModelOperation), varargs...)
}

// CreateModel mocks base method.
func (m *MockModelServiceClient) CreateModel(arg0 context.Context, arg1 *modelv1alpha.CreateModelRequest, arg2 ...grpc.CallOption) (*modelv1alpha.CreateModelResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateModel", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.CreateModelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModel indicates an expected call of CreateModel.
func (mr *MockModelServiceClientMockRecorder) CreateModel(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModel", reflect.TypeOf((*MockModelServiceClient)(nil).CreateModel), varargs...)
}

// CreateModelBinaryFileUpload mocks base method.
func (m *MockModelServiceClient) CreateModelBinaryFileUpload(arg0 context.Context, arg1 ...grpc.CallOption) (modelv1alpha.ModelService_CreateModelBinaryFileUploadClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateModelBinaryFileUpload", varargs...)
	ret0, _ := ret[0].(modelv1alpha.ModelService_CreateModelBinaryFileUploadClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModelBinaryFileUpload indicates an expected call of CreateModelBinaryFileUpload.
func (mr *MockModelServiceClientMockRecorder) CreateModelBinaryFileUpload(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModelBinaryFileUpload", reflect.TypeOf((*MockModelServiceClient)(nil).CreateModelBinaryFileUpload), varargs...)
}

// DeleteModel mocks base method.
func (m *MockModelServiceClient) DeleteModel(arg0 context.Context, arg1 *modelv1alpha.DeleteModelRequest, arg2 ...grpc.CallOption) (*modelv1alpha.DeleteModelResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteModel", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.DeleteModelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteModel indicates an expected call of DeleteModel.
func (mr *MockModelServiceClientMockRecorder) DeleteModel(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModel", reflect.TypeOf((*MockModelServiceClient)(nil).DeleteModel), varargs...)
}

// DeployModelInstance mocks base method.
func (m *MockModelServiceClient) DeployModelInstance(arg0 context.Context, arg1 *modelv1alpha.DeployModelInstanceRequest, arg2 ...grpc.CallOption) (*modelv1alpha.DeployModelInstanceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeployModelInstance", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.DeployModelInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeployModelInstance indicates an expected call of DeployModelInstance.
func (mr *MockModelServiceClientMockRecorder) DeployModelInstance(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeployModelInstance", reflect.TypeOf((*MockModelServiceClient)(nil).DeployModelInstance), varargs...)
}

// GetModel mocks base method.
func (m *MockModelServiceClient) GetModel(arg0 context.Context, arg1 *modelv1alpha.GetModelRequest, arg2 ...grpc.CallOption) (*modelv1alpha.GetModelResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetModel", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.GetModelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModel indicates an expected call of GetModel.
func (mr *MockModelServiceClientMockRecorder) GetModel(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModel", reflect.TypeOf((*MockModelServiceClient)(nil).GetModel), varargs...)
}

// GetModelDefinition mocks base method.
func (m *MockModelServiceClient) GetModelDefinition(arg0 context.Context, arg1 *modelv1alpha.GetModelDefinitionRequest, arg2 ...grpc.CallOption) (*modelv1alpha.GetModelDefinitionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetModelDefinition", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.GetModelDefinitionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelDefinition indicates an expected call of GetModelDefinition.
func (mr *MockModelServiceClientMockRecorder) GetModelDefinition(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelDefinition", reflect.TypeOf((*MockModelServiceClient)(nil).GetModelDefinition), varargs...)
}

// GetModelInstance mocks base method.
func (m *MockModelServiceClient) GetModelInstance(arg0 context.Context, arg1 *modelv1alpha.GetModelInstanceRequest, arg2 ...grpc.CallOption) (*modelv1alpha.GetModelInstanceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetModelInstance", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.GetModelInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelInstance indicates an expected call of GetModelInstance.
func (mr *MockModelServiceClientMockRecorder) GetModelInstance(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelInstance", reflect.TypeOf((*MockModelServiceClient)(nil).GetModelInstance), varargs...)
}

// GetModelInstanceCard mocks base method.
func (m *MockModelServiceClient) GetModelInstanceCard(arg0 context.Context, arg1 *modelv1alpha.GetModelInstanceCardRequest, arg2 ...grpc.CallOption) (*modelv1alpha.GetModelInstanceCardResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetModelInstanceCard", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.GetModelInstanceCardResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelInstanceCard indicates an expected call of GetModelInstanceCard.
func (mr *MockModelServiceClientMockRecorder) GetModelInstanceCard(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelInstanceCard", reflect.TypeOf((*MockModelServiceClient)(nil).GetModelInstanceCard), varargs...)
}

// GetModelOperation mocks base method.
func (m *MockModelServiceClient) GetModelOperation(arg0 context.Context, arg1 *modelv1alpha.GetModelOperationRequest, arg2 ...grpc.CallOption) (*modelv1alpha.GetModelOperationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetModelOperation", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.GetModelOperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelOperation indicates an expected call of GetModelOperation.
func (mr *MockModelServiceClientMockRecorder) GetModelOperation(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelOperation", reflect.TypeOf((*MockModelServiceClient)(nil).GetModelOperation), varargs...)
}

// ListModel mocks base method.
func (m *MockModelServiceClient) ListModel(arg0 context.Context, arg1 *modelv1alpha.ListModelRequest, arg2 ...grpc.CallOption) (*modelv1alpha.ListModelResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListModel", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.ListModelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModel indicates an expected call of ListModel.
func (mr *MockModelServiceClientMockRecorder) ListModel(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModel", reflect.TypeOf((*MockModelServiceClient)(nil).ListModel), varargs...)
}

// ListModelDefinition mocks base method.
func (m *MockModelServiceClient) ListModelDefinition(arg0 context.Context, arg1 *modelv1alpha.ListModelDefinitionRequest, arg2 ...grpc.CallOption) (*modelv1alpha.ListModelDefinitionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListModelDefinition", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.ListModelDefinitionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModelDefinition indicates an expected call of ListModelDefinition.
func (mr *MockModelServiceClientMockRecorder) ListModelDefinition(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelDefinition", reflect.TypeOf((*MockModelServiceClient)(nil).ListModelDefinition), varargs...)
}

// ListModelInstance mocks base method.
func (m *MockModelServiceClient) ListModelInstance(arg0 context.Context, arg1 *modelv1alpha.ListModelInstanceRequest, arg2 ...grpc.CallOption) (*modelv1alpha.ListModelInstanceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListModelInstance", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.ListModelInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModelInstance indicates an expected call of ListModelInstance.
func (mr *MockModelServiceClientMockRecorder) ListModelInstance(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelInstance", reflect.TypeOf((*MockModelServiceClient)(nil).ListModelInstance), varargs...)
}

// ListModelOperation mocks base method.
func (m *MockModelServiceClient) ListModelOperation(arg0 context.Context, arg1 *modelv1alpha.ListModelOperationRequest, arg2 ...grpc.CallOption) (*modelv1alpha.ListModelOperationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListModelOperation", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.ListModelOperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModelOperation indicates an expected call of ListModelOperation.
func (mr *MockModelServiceClientMockRecorder) ListModelOperation(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelOperation", reflect.TypeOf((*MockModelServiceClient)(nil).ListModelOperation), varargs...)
}

// Liveness mocks base method.
func (m *MockModelServiceClient) Liveness(arg0 context.Context, arg1 *modelv1alpha.LivenessRequest, arg2 ...grpc.CallOption) (*modelv1alpha.LivenessResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Liveness", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.LivenessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Liveness indicates an expected call of Liveness.
func (mr *MockModelServiceClientMockRecorder) Liveness(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Liveness", reflect.TypeOf((*MockModelServiceClient)(nil).Liveness), varargs...)
}

// LookUpModel mocks base method.
func (m *MockModelServiceClient) LookUpModel(arg0 context.Context, arg1 *modelv1alpha.LookUpModelRequest, arg2 ...grpc.CallOption) (*modelv1alpha.LookUpModelResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LookUpModel", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.LookUpModelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookUpModel indicates an expected call of LookUpModel.
func (mr *MockModelServiceClientMockRecorder) LookUpModel(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookUpModel", reflect.TypeOf((*MockModelServiceClient)(nil).LookUpModel), varargs...)
}

// LookUpModelInstance mocks base method.
func (m *MockModelServiceClient) LookUpModelInstance(arg0 context.Context, arg1 *modelv1alpha.LookUpModelInstanceRequest, arg2 ...grpc.CallOption) (*modelv1alpha.LookUpModelInstanceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LookUpModelInstance", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.LookUpModelInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookUpModelInstance indicates an expected call of LookUpModelInstance.
func (mr *MockModelServiceClientMockRecorder) LookUpModelInstance(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookUpModelInstance", reflect.TypeOf((*MockModelServiceClient)(nil).LookUpModelInstance), varargs...)
}

// PublishModel mocks base method.
func (m *MockModelServiceClient) PublishModel(arg0 context.Context, arg1 *modelv1alpha.PublishModelRequest, arg2 ...grpc.CallOption) (*modelv1alpha.PublishModelResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PublishModel", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.PublishModelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishModel indicates an expected call of PublishModel.
func (mr *MockModelServiceClientMockRecorder) PublishModel(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishModel", reflect.TypeOf((*MockModelServiceClient)(nil).PublishModel), varargs...)
}

// Readiness mocks base method.
func (m *MockModelServiceClient) Readiness(arg0 context.Context, arg1 *modelv1alpha.ReadinessRequest, arg2 ...grpc.CallOption) (*modelv1alpha.ReadinessResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Readiness", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.ReadinessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Readiness indicates an expected call of Readiness.
func (mr *MockModelServiceClientMockRecorder) Readiness(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Readiness", reflect.TypeOf((*MockModelServiceClient)(nil).Readiness), varargs...)
}

// RenameModel mocks base method.
func (m *MockModelServiceClient) RenameModel(arg0 context.Context, arg1 *modelv1alpha.RenameModelRequest, arg2 ...grpc.CallOption) (*modelv1alpha.RenameModelResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RenameModel", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.RenameModelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenameModel indicates an expected call of RenameModel.
func (mr *MockModelServiceClientMockRecorder) RenameModel(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameModel", reflect.TypeOf((*MockModelServiceClient)(nil).RenameModel), varargs...)
}

// TestModelInstance mocks base method.
func (m *MockModelServiceClient) TestModelInstance(arg0 context.Context, arg1 *modelv1alpha.TestModelInstanceRequest, arg2 ...grpc.CallOption) (*modelv1alpha.TestModelInstanceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TestModelInstance", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.TestModelInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestModelInstance indicates an expected call of TestModelInstance.
func (mr *MockModelServiceClientMockRecorder) TestModelInstance(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestModelInstance", reflect.TypeOf((*MockModelServiceClient)(nil).TestModelInstance), varargs...)
}

// TestModelInstanceBinaryFileUpload mocks base method.
func (m *MockModelServiceClient) TestModelInstanceBinaryFileUpload(arg0 context.Context, arg1 ...grpc.CallOption) (modelv1alpha.ModelService_TestModelInstanceBinaryFileUploadClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TestModelInstanceBinaryFileUpload", varargs...)
	ret0, _ := ret[0].(modelv1alpha.ModelService_TestModelInstanceBinaryFileUploadClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestModelInstanceBinaryFileUpload indicates an expected call of TestModelInstanceBinaryFileUpload.
func (mr *MockModelServiceClientMockRecorder) TestModelInstanceBinaryFileUpload(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestModelInstanceBinaryFileUpload", reflect.TypeOf((*MockModelServiceClient)(nil).TestModelInstanceBinaryFileUpload), varargs...)
}

// TriggerModelInstance mocks base method.
func (m *MockModelServiceClient) TriggerModelInstance(arg0 context.Context, arg1 *modelv1alpha.TriggerModelInstanceRequest, arg2 ...grpc.CallOption) (*modelv1alpha.TriggerModelInstanceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TriggerModelInstance", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.TriggerModelInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerModelInstance indicates an expected call of TriggerModelInstance.
func (mr *MockModelServiceClientMockRecorder) TriggerModelInstance(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerModelInstance", reflect.TypeOf((*MockModelServiceClient)(nil).TriggerModelInstance), varargs...)
}

// TriggerModelInstanceBinaryFileUpload mocks base method.
func (m *MockModelServiceClient) TriggerModelInstanceBinaryFileUpload(arg0 context.Context, arg1 ...grpc.CallOption) (modelv1alpha.ModelService_TriggerModelInstanceBinaryFileUploadClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TriggerModelInstanceBinaryFileUpload", varargs...)
	ret0, _ := ret[0].(modelv1alpha.ModelService_TriggerModelInstanceBinaryFileUploadClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerModelInstanceBinaryFileUpload indicates an expected call of TriggerModelInstanceBinaryFileUpload.
func (mr *MockModelServiceClientMockRecorder) TriggerModelInstanceBinaryFileUpload(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerModelInstanceBinaryFileUpload", reflect.TypeOf((*MockModelServiceClient)(nil).TriggerModelInstanceBinaryFileUpload), varargs...)
}

// UndeployModelInstance mocks base method.
func (m *MockModelServiceClient) UndeployModelInstance(arg0 context.Context, arg1 *modelv1alpha.UndeployModelInstanceRequest, arg2 ...grpc.CallOption) (*modelv1alpha.UndeployModelInstanceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UndeployModelInstance", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.UndeployModelInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UndeployModelInstance indicates an expected call of UndeployModelInstance.
func (mr *MockModelServiceClientMockRecorder) UndeployModelInstance(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UndeployModelInstance", reflect.TypeOf((*MockModelServiceClient)(nil).UndeployModelInstance), varargs...)
}

// UnpublishModel mocks base method.
func (m *MockModelServiceClient) UnpublishModel(arg0 context.Context, arg1 *modelv1alpha.UnpublishModelRequest, arg2 ...grpc.CallOption) (*modelv1alpha.UnpublishModelResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnpublishModel", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.UnpublishModelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnpublishModel indicates an expected call of UnpublishModel.
func (mr *MockModelServiceClientMockRecorder) UnpublishModel(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpublishModel", reflect.TypeOf((*MockModelServiceClient)(nil).UnpublishModel), varargs...)
}

// UpdateModel mocks base method.
func (m *MockModelServiceClient) UpdateModel(arg0 context.Context, arg1 *modelv1alpha.UpdateModelRequest, arg2 ...grpc.CallOption) (*modelv1alpha.UpdateModelResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateModel", varargs...)
	ret0, _ := ret[0].(*modelv1alpha.UpdateModelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateModel indicates an expected call of UpdateModel.
func (mr *MockModelServiceClientMockRecorder) UpdateModel(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModel", reflect.TypeOf((*MockModelServiceClient)(nil).UpdateModel), varargs...)
}
