$defs:
  segment:
    properties:
      start-time:
        title: Start Time
        description: The number of seconds from the beginning of the audio file to the start of this segment.
        uiOrder: 0
        format: number
      end-time:
        title: End Time
        description: The number of seconds from the beginning of the audio file to the end of this segment.
        uiOrder: 1
        format: number
    required:
      - start-time
      - end-time
    title: Segment
    description: A time segment of audio data, defined by its start and end times in seconds.
    format: object
TASK_DETECT_ACTIVITY:
  shortDescription: Detect speech segments in audio data using Voice Activity Detection (VAD). This task processes the input audio to 16kHz mono format,
    identifies periods of human speech, and outputs time segments for each detected speech activity.
  input:
    description: Input.
    uiOrder: 0
    properties:
      audio:
        description: Audio file to analyze for speech activity.
        acceptFormats:
          - audio/wav
          - application/octet-stream
        uiOrder: 0
        title: Audio
        format: string
      min-silence-duration:
        description: Minimum duration of silence (in milliseconds) required to split speech segments. Longer values result in fewer, longer segments.
        acceptFormats:
          - integer
          - number
        uiOrder: 1
        minimum: 0
        title: Minimum Silence Duration
        default: 100
        format: integer
      speech-pad:
        description: Additional padding (in milliseconds) added to the start and end of each detected speech segment to prevent cutting off speech.
        acceptFormats:
          - integer
          - number
        uiOrder: 2
        minimum: 0
        title: Speech Pad
        default: 30
        format: integer
    required:
      - audio
    title: Input
    format: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      segments:
        description: Array of time segments representing detected speech activity. Each segment contains start and end times in seconds.
        uiOrder: 0
        items:
          $ref: '#/$defs/segment'
        title: Segments
        format: array
    required:
      - segments
    title: Output
    format: object
TASK_SEGMENT:
  shortDescription: Segment audio data into pieces based on the provided time segments.
  input:
    description: Input.
    uiOrder: 0
    properties:
      audio:
        description: Audio data to segment.
        acceptFormats:
          - audio/*
          - application/octet-stream
        uiOrder: 0
        title: Audio
        format: string
      segments:
        description: A list of time segments of audio data.
        uiOrder: 1
        items:
          $ref: '#/$defs/segment'
        title: Segments
        format: array
    required:
      - audio
      - segments
    title: Input
    format: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      audio-segments:
        description: A list of segmented audio data.
        uiOrder: 0
        items:
          format: string
        title: Audios
        format: array
    required:
      - audio-segments
    title: Output
    format: object
