$defs:
  instill-types:
    bounding-box:
      additionalProperties: false
      description: The detected bounding box in (left, top, width, height) format.
      properties:
        height:
          description: Bounding box height value
          uiOrder: 3
          title: Height
          format: number
        left:
          description: Bounding box left x-axis value
          uiOrder: 0
          title: Left
          format: number
        top:
          description: Bounding box top y-axis value
          uiOrder: 1
          title: Top
          format: number
        width:
          description: Bounding box width value
          uiOrder: 2
          title: Width
          format: number
      required:
      - left
      - top
      - width
      - height
      title: Bounding Box
      format: object
    chat-messages:
      items:
        properties:
          content:
            $ref: '#/$defs/instill-types/multi-modal-content'
            description: The message content
            uiOrder: 1
            title: Content
          metadata:
            additionalProperties: true
            description: The message metadata
            uiOrder: 2
            required: []
            title: Metadata
            format: json
          role:
            description: The message role, i.e. 'system', 'user' or 'assistant'
            uiOrder: 0
            title: Role
            format: string
        required:
        - role
        - content
        format: object
      title: Chat Message
      format: array
    classification:
      additionalProperties: false
      properties:
        category:
          description: The predicted category of the input.
          uiOrder: 0
          title: Category
          format: string
        score:
          description: The confidence score of the predicted category of the input.
          uiOrder: 1
          title: Score
          format: number
      required:
      - category
      - score
      format: object
    detection:
      additionalProperties: false
      properties:
        objects:
          description: A list of detected objects.
          uiOrder: 0
          items:
            additionalProperties: false
            properties:
              bounding-box:
                $ref: '#/$defs/instill-types/bounding-box'
                uiOrder: 1
                title: Bounding box
              category:
                description: The predicted category of the bounding box.
                uiOrder: 2
                title: Category
                format: string
              score:
                description: The confidence score of the predicted category of the
                  bounding box.
                uiOrder: 3
                title: Score
                format: number
            required:
            - bounding-box
            - category
            - score
            title: Object
            format: object
          title: Objects
          format: array
      required:
      - objects
      format: object
    embedding:
      items:
        title: Embedding
        format: number
      title: Embedding
      format: array
    instance-segmentation:
      additionalProperties: false
      properties:
        objects:
          description: A list of detected instance bounding boxes.
          uiOrder: 0
          items:
            properties:
              bounding-box:
                $ref: '#/$defs/instill-types/bounding-box'
                uiOrder: 1
                title: Bounding Box
              category:
                description: The predicted category of the bounding box.
                uiOrder: 2
                title: Category
                format: string
              rle:
                description: Run Length Encoding (RLE) of instance mask within the
                  bounding box.
                uiOrder: 0
                title: RLE
                format: string
              score:
                description: The confidence score of the predicted instance object.
                uiOrder: 3
                title: Score
                format: number
            required:
            - rle
            - bounding-box
            - category
            - score
            title: Object
            format: object
          title: Objects
          format: array
      required:
      - objects
      format: object
    keypoint:
      additionalProperties: false
      properties:
        objects:
          description: A list of keypoint objects, a keypoint object includes all
            the pre-defined keypoints of a detected object.
          uiOrder: 0
          items:
            properties:
              bounding-box:
                $ref: '#/$defs/instill-types/bounding-box'
                uiOrder: 2
                title: Bounding Box
              keypoints:
                description: A keypoint group is composed of a list of pre-defined
                  keypoints of a detected object.
                uiOrder: 0
                items:
                  uiOrder: 0
                  properties:
                    v:
                      description: visibility score of the keypoint.
                      uiOrder: 2
                      title: Visibility Score
                      format: number
                    x:
                      description: x coordinate of the keypoint.
                      uiOrder: 0
                      title: X Coordinate
                      format: number
                    y:
                      description: y coordinate of the keypoint.
                      uiOrder: 1
                      title: Y Coordinate
                      format: number
                  required:
                  - x
                  - y
                  - v
                  title: Keypoints
                  format: object
                title: Keypoints
                format: array
              score:
                description: The confidence score of the predicted object.
                uiOrder: 1
                title: Score
                format: number
            required:
            - keypoints
            - score
            - bounding-box
            title: Object
            format: object
          title: Objects
          format: array
      required:
      - objects
      format: object
    multi-modal-content:
      items:
        properties:
          image-url:
            properties:
              url:
                description: Either a URL of the image or the base64 encoded image
                  data.
                title: URL
                uiOrder: 0
                format: string
            required:
            - url
            title: Image URL
            description: The image URL
            uiOrder: 0
            format: object
          text:
            description: The text content.
            title: Text
            uiOrder: 1
            format: string
          type:
            description: The type of the content part.
            enum:
            - text
            - image-url
            title: Type
            uiOrder: 2
            format: string
        required:
        - type
        format: object
      format: array
    ocr:
      additionalProperties: false
      properties:
        objects:
          description: A list of detected bounding boxes.
          uiOrder: 0
          items:
            properties:
              bounding-box:
                $ref: '#/$defs/instill-types/bounding-box'
                uiOrder: 0
                title: Bounding Box
              score:
                description: The confidence score of the predicted object.
                uiOrder: 2
                title: Score
                format: number
              text:
                description: Text string recognised per bounding box.
                uiOrder: 1
                title: Text
                format: string
            required:
            - bounding-box
            - text
            - score
            title: Object
            format: object
          title: Objects
          format: array
      required:
      - objects
      format: object
    semantic-segmentation:
      additionalProperties: false
      properties:
        stuffs:
          description: A list of RLE binary masks.
          uiOrder: 0
          items:
            properties:
              category:
                description: Category text string corresponding to each stuff mask.
                uiOrder: 1
                title: Category
                format: string
              rle:
                description: Run Length Encoding (RLE) of each stuff mask within the
                  image.
                uiOrder: 0
                title: RLE
                format: string
            required:
            - rle
            - category
            title: Object
            format: object
          title: Stuffs
          format: array
      required:
      - stuffs
      format: object
