TASK_CREATE_CAMPAIGN:
  title: Create Campaign
  shortDescription: Create a new campaign. You have to create a campaign before you can start adding leads to it. Please check [Smartlead API document](https://api.smartlead.ai/reference/references#campaign).
  input:
    title: Input
    description: Input parameters for creating a campaign.
    properties:
      name:
        title: Name
        description: Name of the campaign.
        type: string
        uiOrder: 0
    required:
      - name
    type: object
  output:
    title: Output
    description: Output for creating a campaign. You can use this output in the next task.
    properties:
      id:
        title: ID
        description: ID of the campaign.
        uiOrder: 0
        type: string
      created-at:
        title: Created At
        description: Created at timestamp of the campaign.
        uiOrder: 1
        type: string
    required:
      - id
      - created-at
    type: object
TASK_SETUP_CAMPAIGN:
  title: Setup Campaign
  shortDescription: Setup a campaign. You can update campaign settings to this campaign. For Smartlead campaign, you will need to setup the schedule settings
    and general settings.
  input:
    title: Input
    description: Input parameters for setting up a campaign.
    properties:
      campaign-name:
        title: Campaign Name
        description: Name of the campaign.
        type: string
        uiOrder: 0
      timezone:
        title: Timezone
        description: Timezone of the campaign. Please choose the value in [List of Timezones](https://help.smartlead.ai/Timezones-20fcff9ddbb5441790c7c8e5ce0e9233).
        type: string
        uiOrder: 1
      days-of-the-week:
        title: Days of the Week
        description: Days of the week when the campaign will run. A number value ranging from 0 to 6; i.e [0,1,2,3,4,5,6]. 0 is Sunday, 1 is Monday, and
          so on.
        items:
          type: number
        uiOrder: 2
        type: array
      start-hour:
        title: Start Hour
        description: Start hour of the campaign. Time to start the campaign in 24-hour format (HH:MM).
        type: string
        uiOrder: 3
      end-hour:
        title: End Hour
        description: End hour of the campaign. Time to end the campaign in 24-hour format (HH:MM).
        type: string
        uiOrder: 4
      min-time-btw-emails:
        title: Minimum Time Between Emails
        description: Minimum time between emails in minutes. The minimum value is 3 minutes.
        type: number
        minimum: 3
        uiOrder: 5
      max-new-leads-per-day:
        title: Maximum New Leads Per Day
        description: Maximum new leads per day.
        type: number
        uiOrder: 6
      schedule-start-time:
        title: Schedule Start Time
        description: Schedule start time of the campaign. Please specify the campaign start time in standard ISO 8601 format. e.g. 2024-11-27T07:29:25.978Z.
        type: string
        uiOrder: 7
      track-settings:
        title: Track Settings
        enum:
          - DONT_TRACK_EMAIL_OPEN
          - DONT_TRACK_LINK_CLICK
          - DONT_TRACK_REPLY_TO_AN_EMAIL
        description: Tracking settings like not tracking opens or link clicks.
        items:
          type: string
        uiOrder: 8
        type: array
      stop-lead-settings:
        title: Stop Lead Settings
        description: Stops lead if they do the action specified.
        enum:
          - CLICK_ON_A_LINK
          - OPEN_AN_EMAIL
        uiOrder: 9
        type: string
      send-as-plain-text:
        title: Send as Plain Text
        description: Send emails as plain text.
        uiOrder: 10
        type: boolean
      follow-up-percentage:
        title: Follow Up Percentage
        description: Specifies the percentage of leads in a campaign who should receive follow-up emails.
        type: number
        uiOrder: 11
      add-unsubscribe-tag:
        title: Add Unsubscribe Tag
        description: Add an unsubscribe tag to the email.
        uiOrder: 12
        type: boolean
      ignore-ss-mailbox-sending-limit:
        title: Ignore Mailbox Sending Limit
        description: Ignore mailbox sending limits, used when creating a subsequence.
        uiOrder: 13
        type: boolean
    required:
      - campaign-name
      - timezone
      - days-of-the-week
      - start-hour
      - end-hour
      - min-time-btw-emails
      - max-new-leads-per-day
      - schedule-start-time
    type: object
  output:
    title: Output
    description: Output for setting up a campaign.
    properties:
      result:
        title: Result
        description: Result of setting up a campaign.
        uiOrder: 0
        type: string
    required:
      - schedule-setting-result
      - general-setting-result
    type: object
TASK_SAVE_SEQUENCES:
  title: Save Sequences
  shortDescription: Save sequences to a campaign. A Smartlead sequence is a series of automated emails sent to potential customers based on specific actions,
    or triggers.
  input:
    title: Input
    description: Input parameters for saving sequences.
    properties:
      campaign-name:
        title: Campaign Name
        description: Name of the campaign.
        type: string
        uiOrder: 0
      sequences:
        title: Sequences
        description: A Smartlead sequence is a series of automated emails sent to potential customers based on specific actions, or triggers.
        type: array
        items:
          properties:
            seq-number:
              title: Sequence Number
              description: Sequence number means the order of the sequence. If you don't specify this, it will be automatically assigned by the order of
                the sequences.
              type: number
              uiOrder: 0
            sequence-delay-days:
              title: Sequence Delay Days
              description: Number of days to wait before sending the next email. If you don't specify this, the default value is 1 day.
              type: number
              uiOrder: 1
              default: 1
            subject:
              title: Subject
              description: Subject of the email. If you want to set the variable according to different leads, you can use {{variable_name}}. It will be
                replaced by the actual value from the lead.
              type: string
              uiOrder: 2
            email-body:
              title: Email Body
              description: Body of the email. If you want to set the variable according to different leads, you can use {{variable_name}}. It will be replaced
                by the actual value from the lead.
              type: string
              uiOrder: 3
          required: []
          type: object
        uiOrder: 1
    required:
      - campaign-name
      - sequences
    type: object
  output:
    title: Output
    description: Output for saving sequences.
    properties:
      result:
        title: Result
        description: Result of saving sequences.
        uiOrder: 0
        type: string
    required:
      - result
    type: object
TASK_GET_SEQUENCES:
  title: Get Sequences
  shortDescription: Get sequences of a campaign. If you want to add more sequences to the campaign, you can get the existing sequences and add new sequences
    to them. And, you can execute `TASK_SAVE_SEQUENCES` to save the sequences.
  input:
    title: Input
    description: Input parameters for getting sequences.
    properties:
      campaign-name:
        title: Campaign Name
        description: Name of the campaign.
        type: string
        uiOrder: 0
    required:
      - campaign-name
    type: object
  output:
    title: Output
    description: Output for getting sequences.
    properties:
      sequences:
        title: Sequences
        description: Sequences of the campaign.
        type: array
        items:
          properties:
            seq-id:
              title: Sequence ID
              description: ID of the sequence.
              type: string
              uiOrder: 0
            seq-number:
              title: Sequence Number
              description: Sequence number means the order of the sequence.
              type: number
              uiOrder: 0
            sequence-delay-days:
              title: Sequence Delay Days
              description: Number of days to wait before sending the next email.
              type: number
              uiOrder: 1
            subject:
              title: Subject
              description: Subject of the email when you save the sequence.
              type: string
              uiOrder: 2
            email-body:
              title: Email Body
              description: Body of the email when you save the sequence.
              type: string
              uiOrder: 3
          required: []
          type: object
        uiOrder: 1
    required:
      - sequences
    type: object
TASK_ADD_LEADS:
  title: Add Leads
  shortDescription: Add leads to a campaign.
  input:
    title: Input
    description: Input parameters for adding leads.
    properties:
      campaign-name:
        title: Campaign Name
        description: Name of the campaign.
        type: string
        uiOrder: 0
      leads:
        title: Leads
        description: Leads to add to the campaign.
        type: array
        items:
          properties:
            email:
              title: Email
              description: Email of the lead.
              type: string
              uiOrder: 0
            first-name:
              title: First Name
              description: First name of the lead.
              type: string
              uiOrder: 1
            last-name:
              title: Last Name
              description: Last name of the lead.
              type: string
              uiOrder: 2
            company:
              title: Company
              description: Company name of the lead.
              type: string
              uiOrder: 3
            location:
              title: Location
              description: Location of the lead.
              type: string
              uiOrder: 4
            custom-fields:
              title: Custom Fields
              description: Custom fields of the lead. You can use custom fields to store additional information about the lead, which can be used in the
                variable in the sequence email template.
              items:
                properties:
                  key:
                    title: Key
                    description: Key of the custom field.
                    type: string
                    uiOrder: 0
                  value:
                    title: Value
                    description: Value of the custom field.
                    type: string
                    uiOrder: 1
                required:
                  - key
                  - value
              required: []
              uiOrder: 5
              type: array
          required:
            - email
          type: object
        uiOrder: 1
      settings:
        title: Settings
        description: Settings for adding leads.
        properties:
          ignore-global-block-list:
            title: Ignore Global Block List
            description: Ignore the global block list and add the lead. If true, uploaded leads will BYPASS the global block list and be uploaded to the
              campaign.
            type: boolean
            uiOrder: 0
          ignore-unsubscribe-list:
            title: Ignore Unsubscribe List
            description: Ignore the unsubscribe list and add the lead. If true, leads will BYPASS the comparison with unsubscribed leads and be uploaded
              to the campaign.
            type: boolean
            uiOrder: 1
          ignore-community-bounce-list:
            title: Ignore Community Bounce List
            description: Ignore the community bounce list and add the lead. If true, uploaded leads will BYPASS any leads that bounced across Smartlead
              entire user base and be uploaded to the campaign.
            type: boolean
            uiOrder: 2
          ignore-duplicate-leads-in-other-campaign:
            title: Ignore Duplicate Leads in Other Campaign
            description: 'Ignore duplicate leads in other campaigns and add the lead. If true, leads will NOT BYPASS the comparison with other campaigns
              and NOT be added to the campaign if they are part of any other campaign. '
            type: boolean
            uiOrder: 3
        uiOrder: 2
        required:
          - ignore-duplicate-leads-in-other-campaign
        type: object
    required:
      - campaign-name
      - leads
    type: object
  output:
    title: Output
    description: Output for adding leads.
    properties:
      upload-count:
        title: Upload Count
        description: Number of leads uploaded.
        uiOrder: 0
        type: number
      total-leads:
        title: Total Leads
        description: Total number of leads in the campaign.
        uiOrder: 1
        type: number
      already-added-to-campaign:
        title: Already Added to Campaign
        description: Number of leads already added to the campaign.
        uiOrder: 2
        type: number
      invalid-email-count:
        title: Invalid Email Count
        description: Number of leads with invalid email.
        uiOrder: 3
        type: number
      error:
        title: Error
        description: Error message from Smartlead if any.
        uiOrder: 4
        type: string
    required:
      - upload-count
      - total-leads
      - already-added-to-campaign
      - invalid-email-count
    type: object
TASK_ADD_SENDER_EMAIL:
  title: Add Sender Email
  shortDescription: Add a sender email to the campaign. You have to configure the sender email in Smartlead console before adding it to the campaign.
  input:
    title: Input
    description: Input parameters for adding a sender email.
    properties:
      campaign-name:
        title: Campaign Name
        description: Name of the campaign.
        type: string
        uiOrder: 0
      sender-email:
        title: Sender Email
        description: Email address of the sender. You need to configure the sender email in [Smartlead console](https://app.smartlead.ai/app/email-accounts)
          before adding it to the campaign.
        type: string
        uiOrder: 1
    required:
      - campaign-name
      - sender-email
    type: object
  output:
    title: Output
    description: Output for adding a sender email.
    properties:
      result:
        title: Result
        description: Result of adding a sender email. If you don't configure your sender email in Smartlead console, you will get an error.
        uiOrder: 0
        type: string
    required:
      - result
    type: object
TASK_UPDATE_CAMPAIGN_STATUS:
  title: Update Campaign Status
  shortDescription: Update the status of a campaign. You need to start a campaign to send the emails to the leads.
  input:
    title: Input
    description: Input parameters for updating the status of a campaign.
    properties:
      campaign-name:
        title: Campaign Name
        description: Name of the campaign.
        type: string
        uiOrder: 0
      status:
        title: Status
        description: Status of the campaign.
        enum:
          - START
          - PAUSED
          - STOPPED
        uiOrder: 1
        type: string
    required:
      - campaign-name
      - status
    type: object
  output:
    title: Output
    description: Output for updating the status of a campaign.
    properties:
      result:
        title: Result
        description: Result of updating the status of a campaign.
        uiOrder: 0
        type: string
    required:
      - result
    type: object
TASK_GET_CAMPAIGN_METRIC:
  title: Get Campaign Metric
  shortDescription: Get the metrics of a campaign. You can get the metrics like open count, click count, and reply count of the campaign.
  input:
    title: Input
    description: Input parameters for getting the metrics of a campaign.
    properties:
      campaign-name:
        title: Campaign Name
        description: Name of the campaign.
        type: string
        uiOrder: 0
    required:
      - campaign-name
    type: object
  output:
    title: Output
    description: Output for getting the metrics of a campaign.
    properties:
      sent-count:
        title: Sent Count
        description: Number of emails sent.
        uiOrder: 0
        type: number
      unique-sent-count:
        title: Unique Sent Count
        description: Number of unique emails sent.
        uiOrder: 1
        type: number
      open-count:
        title: Open Count
        description: Number of emails opened.
        uiOrder: 2
        type: number
      unique-open-count:
        title: Unique Open Count
        description: Number of unique emails opened.
        uiOrder: 3
        type: number
      click-count:
        title: Click Count
        description: Number of emails clicked.
        uiOrder: 4
        type: number
      unique-click-count:
        title: Unique Click Count
        description: Number of unique emails clicked.
        uiOrder: 5
        type: number
      reply-count:
        title: Reply Count
        description: Number of emails replied.
        uiOrder: 6
        type: number
      total-count:
        title: Total Count
        description: Total number of emails.
        uiOrder: 7
        type: number
      bounce-count:
        title: Bounce Count
        description: Number of emails bounced.
        uiOrder: 8
        type: number
    required: []
    type: object
TASK_LIST_LEADS_STATUS:
  title: List Leads Status
  shortDescription: List the status of leads in a campaign. You can get the status of leads like 'STARTED', 'INPROGRESS', 'COMPLETED', 'PAUSED', 'STOPPED'.
  input:
    title: Input
    description: Input parameters for listing the status of leads.
    properties:
      campaign-name:
        title: Campaign Name
        description: Name of the campaign.
        type: string
        uiOrder: 0
      limit:
        title: Limit
        description: Number of leads to list. The minimum value is 1.
        minimum: 1
        type: number
        uiOrder: 1
    required:
      - campaign-name
      - limit
    type: object
  output:
    title: Output
    description: Output for listing the status of leads.
    properties:
      leads:
        title: Leads
        description: Lead status in the campaign.
        items:
          properties:
            email:
              title: Email
              description: Email of the lead.
              uiOrder: 0
              type: string
            status:
              title: Status
              description: Status of the lead.
              uiOrder: 1
              type: string
          required:
            - email
            - status
          type: object
        uiOrder: 0
        type: array
    required:
      - leads
    type: object
