additionalProperties: true
properties:
  model:
    description: The model to be used. Now, it only supports OpenAI model, and will support more models in the future.
    shortDescription: The model to be used.
    type: string
    enum:
      - o1-preview
      - o1-mini
      - gpt-4o-mini
      - gpt-4o
      - gpt-4o-2024-05-13
      - gpt-4o-2024-08-06
      - gpt-4-turbo
      - gpt-4-turbo-2024-04-09
      - gpt-4-0125-preview
      - gpt-4-turbo-preview
      - gpt-4-1106-preview
      - gpt-4-vision-preview
      - gpt-4
      - gpt-4-0314
      - gpt-4-0613
      - gpt-4-32k
      - gpt-4-32k-0314
      - gpt-4-32k-0613
      - gpt-3.5-turbo
      - gpt-3.5-turbo-16k
      - gpt-3.5-turbo-0301
      - gpt-3.5-turbo-0613
      - gpt-3.5-turbo-1106
      - gpt-3.5-turbo-0125
      - gpt-3.5-turbo-16k-0613
    instillCredentialMap:
      values:
        - o1-preview
        - o1-mini
        - gpt-4o
        - gpt-4o-2024-08-06
        - gpt-4-turbo
        - gpt-4-vision-preview
        - gpt-4
        - gpt-4-32k
        - gpt-3.5-turbo
        - gpt-4o-mini
      targets:
        - setup.api-key
    uiOrder: 0
    title: Model Name
  api-key:
    description: Fill in your API key from the vendor's platform.
    type: string
    instillSecret: true
    instillCredential: true
    uiOrder: 1
    title: API Key
  organization:
    description: Specify which organization is used for the requests. Usage will count against the specified organization's subscription quota.
    type: string
    uiOrder: 2
    title: Organization ID
required:
  - model
title: Universal AI Connection
type: object
