TASK_CHAT:
  title: Chat
  shortDescription: Generate response base on conversation input
  input:
    title: Chat input
    description: Input schema of the chat task.
    shortDescription: Input schema of the chat task
    properties:
      data:
        title: Chat Data
        description: Input data.
        shortDescription: Input data
        properties:
          messages:
            title: Chat Messages
            items:
              properties:
                content:
                  description: The message content.
                  shortDescription: The message content
                  title: Content
                  items:
                    oneOf:
                      - properties:
                          text:
                            title: Text Message
                            description: Text message.
                            shortDescription: Text message.
                            type: string
                            uiOrder: 1
                          type:
                            title: Text
                            description: Text content type.
                            shortDescription: Text content type.
                            type: string
                            const: text
                            uiOrder: 0
                        required:
                          - text
                          - type
                        title: Text
                        type: object
                      - properties:
                          image-url:
                            title: Image URL
                            description: Image message URL.
                            shortDescription: Image message URL.
                            type: string
                            uiOrder: 1
                          type:
                            title: Image URL
                            description: Image URL content type.
                            shortDescription: Image URL content type
                            type: string
                            const: image-url
                            uiOrder: 0
                        required:
                          - image-url
                          - type
                        title: Image URL
                        type: object
                      - properties:
                          image-base64:
                            title: Image Base64
                            description: Image base64 encoded string.
                            shortDescription: Image base64 encoded string.
                            type: string
                            uiOrder: 1
                          type:
                            title: Image File
                            description: Image file input content type.
                            shortDescription: Image file input content type
                            type: string
                            const: image-base64
                            uiOrder: 0
                        required:
                          - image-base64
                          - type
                        title: Image Base64
                        type: object
                    required: []
                    type: object
                  uiOrder: 0
                  type: array
                role:
                  description: The message role, i.e. 'system', 'user' or 'assistant'.
                  shortDescription: The message role, i.e. 'system', 'user' or 'assistant'
                  type: string
                  title: Role
                  enum:
                    - system
                    - user
                    - assistant
                  uiOrder: 1
                name:
                  description: An optional name for the participant. Provides the model information to differentiate between participants of the same role.
                  shortDescription: An optional name for the participant. Provides the model information to differentiate between participants of the same
                    role.
                  type: string
                  title: Name
                  uiOrder: 2
              required:
                - content
                - role
              type: object
            uiOrder: 0
            description: List of chat messages.
            type: array
        required:
          - messages
        uiOrder: 0
        type: object
      parameter:
        description: Input parameter.
        shortDescription: Input parameter
        properties:
          max-tokens:
            title: Max New Tokens
            description: The maximum number of tokens for model to generate.
            shortDescription: The maximum number of tokens for model to generate
            type: integer
            default: 50
            uiOrder: 0
          seed:
            title: Seed
            description: The seed, default is 0.
            shortDescription: The seed, default is 0
            type: integer
            default: 0
            uiOrder: 1
          n:
            title: Number of Choices
            description: How many chat completion choices to generate for each input message.
            shortDescription: How many chat completion choices to generate for each input message.
            type: integer
            default: 1
            uiOrder: 2
          temperature:
            title: Temperature
            description: The temperature for sampling.
            shortDescription: The temperature for sampling
            type: number
            default: 0.7
            uiOrder: 3
          top-p:
            title: Top P
            description: An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with
              top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering
              this or temperature but not both.
            shortDescription: Nucleus sampling
            type: number
            default: 1
            uiOrder: 4
          stream:
            title: Stream
            description: If set, partial message deltas will be sent. Tokens will be sent as data-only server-sent events as they become available.
            shortDescription: If set, partial message deltas will be sent
            type: boolean
            default: false
            uiOrder: 5
        required: []
        uiOrder: 1
        title: Input Parameter
        type: object
    required:
      - data
    type: object
  output:
    title: Chat output
    description: Output schema of the chat task.
    shortDescription: Output schema of the chat task
    properties:
      data:
        description: Output data.
        shortDescription: Output data
        properties:
          choices:
            title: Choices
            description: List of chat completion choices.
            shortDescription: List of chat completion choices
            items:
              properties:
                finish-reason:
                  title: Finish Reason
                  description: The reason the model stopped generating tokens.
                  shortDescription: The reason the model stopped generating tokens.
                  uiOrder: 0
                  type: string
                index:
                  title: Index
                  description: The index of the choice in the list of choices.
                  shortDescription: The index of the choice in the list of choices.
                  uiOrder: 1
                  type: integer
                message:
                  title: Message
                  description: A chat message generated by the model.
                  shortDescription: A chat message generated by the model.
                  properties:
                    content:
                      title: Content
                      description: The contents of the message.
                      shortDescription: The contents of the message.
                      uiOrder: 0
                      type: string
                    role:
                      title: Role
                      description: The role of the author of this message.
                      shortDescription: The role of the author of this message.
                      uiOrder: 1
                      type: string
                  required: []
                  uiOrder: 2
                  type: object
                created:
                  title: Created
                  description: The Unix timestamp (in seconds) of when the chat completion was created.
                  shortDescription: The Unix timestamp (in seconds) of when the chat completion was created.
                  uiOrder: 3
                  type: integer
              required:
                - finish-reason
                - index
                - message
                - created
              type: object
            uiOrder: 0
            type: array
        required:
          - choices
        uiOrder: 0
        title: Output Data
        type: object
      metadata:
        description: Output metadata.
        shortDescription: Output metadata
        properties:
          usage:
            description: Usage statistics for the request.
            shortDescription: Usage statistics for the request.
            properties:
              completion-tokens:
                title: Completion Tokens
                description: Number of tokens in the generated response.
                shortDescription: Number of tokens in the generated response.
                uiOrder: 0
                type: integer
              prompt-tokens:
                title: Prompt Tokens
                description: Number of tokens in the prompt.
                shortDescription: Number of tokens in the prompt.
                uiOrder: 1
                type: integer
              total-tokens:
                title: Total Tokens
                description: Total number of tokens used in the request (prompt + completion).
                shortDescription: Total number of tokens used in the request (prompt + completion).
                uiOrder: 2
                type: integer
            required:
              - completion-tokens
              - prompt-tokens
              - total-tokens
            uiOrder: 0
            title: Usage
            type: object
        required: []
        title: Output Metadata
        uiOrder: 1
        type: object
    required:
      - data
    type: object
