availableTasks:
- TASK_CHAT
custom: false
documentationUrl: https://www.instill.tech/docs/component/ai/perplexity
icon: assets/perplexity.svg
id: perplexity
public: true
title: Perplexity
description: Connect the AI models served on the Perplexity Platform.
type: COMPONENT_TYPE_AI
uid: 61339791-dfe0-4ba1-9efc-7d4452c03e53
vendor: Perplexity
vendorAttributes: {}
version: 0.1.0
sourceUrl: https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/ai/perplexity/v0
releaseStage: RELEASE_STAGE_ALPHA
