additionalProperties: false
properties:
  api-key:
    description: Fill in your API key from the vendor's platform.
    type: string
    instillSecret: true
    instillCredential: true
    uiOrder: 0
    title: API Key
required: []
title: Perplexity Connection
type: object
