additionalProperties: false
properties:
  api-key:
    description: Fill in your OpenAI API key. To find your keys, visit your OpenAI's API Keys page.
    type: string
    instillSecret: true
    instillCredential: true
    uiOrder: 0
    title: API Key
  organization:
    description: Specify which organization is used for the requests. Usage will count against the specified organization's subscription quota.
    type: string
    uiOrder: 1
    title: Organization ID
required: []
title: OpenAI Connection
type: object
