additionalProperties: false
properties:
  api-key:
    description: Fill in your Mistral API key. To find your keys, visit the Mistral AI platform page.
    type: string
    instillSecret: true
    instillCredential: true
    uiOrder: 0
    title: API Key
required: []
title: Mistral AI Connection
type: object
