$defs:
  multi-modal-content:
    items:
      properties:
        image-url:
          properties:
            url:
              description: Either a URL of the image or the base64 encoded image data.
              title: URL
              uiOrder: 0
              type: string
          required:
            - url
          title: Image URL
          description: The image URL.
          uiOrder: 0
          type: object
        text:
          description: The text content.
          title: Text
          uiOrder: 1
          type: string
        type:
          description: The type of the content part.
          enum:
            - text
            - image_url
          title: Type
          uiOrder: 2
          type: string
      required:
        - type
      type: object
    type: array
  chat-message:
    properties:
      content:
        $ref: "#/$defs/multi-modal-content"
        description: The message content.
        uiOrder: 1
        title: Content
      role:
        description: The message role, i.e. 'system', 'user' or 'assistant'.
        uiOrder: 0
        title: Role
        type: string
    required:
      - role
      - content
    title: Chat Message
    type: object
  chat-usage:
    description: Token usage on the Mistral platform text generation models.
    uiOrder: 1
    properties:
      input-tokens:
        description: The input tokens used by Mistral models.
        uiOrder: 2
        title: Input Tokens
        type: number
      output-tokens:
        description: The output tokens generated by Mistral models.
        uiOrder: 3
        title: Output Tokens
        type: number
    required:
      - input-tokens
      - output-tokens
    title: Usage
    type: object
  embedding-usage:
    description: Token usage on the Mistral platform embedding models.
    uiOrder: 1
    properties:
      tokens:
        description: The token count used by Mistral models.
        uiOrder: 1
        title: Token Count
        type: number
    required:
      - tokens
    title: Usage
    type: object
TASK_TEXT_GENERATION_CHAT:
  shortDescription: Provide text outputs in response to text inputs.
  description: >-
    Mistral AI's text generation models (often called generative pre-trained transformers or large language models) have been trained to understand
    natural language, code, and images. The models provide text outputs in response to their inputs. The inputs to these models are also referred to as
    "prompts". Designing a prompt is essentially how you "program" a large language model model, usually by providing instructions or some examples of how
    to successfully complete a task.
  input:
    description: Input.
    uiOrder: 0
    properties:
      chat-history:
        description: >-
          Incorporate external chat history, specifically previous messages within the conversation. Please note that System Message will be
          ignored and will not have any effect when this field is populated. Each message should adhere to the format: {"role": "The message role, i.e.
          `system`, `user` or `assistant`", "content": "message content"}.
        type: array
        shortDescription: >-
          Incorporate external chat history, specifically previous messages within the conversation. (Note: The Mistral models are not trained to process images, thus images will be omitted)
        uiOrder: 4
        items:
          $ref: "#/$defs/chat-message"
        title: Chat history
      max-new-tokens:
        default: 50
        description: The maximum number of tokens for model to generate.
        type: integer
        uiOrder: 6
        title: Max New Tokens
      model-name:
        enum:
          - open-mixtral-8x22b
          - open-mixtral-8x7b
          - open-mistral-7b
          - mistral-large-latest
          - mistral-small-latest
          - codestral-latest
        example: open-mixtral-8x22b
        description: The Mistral model to be used.
        type: string
        uiOrder: 0
        instillCredentialMap:
          values:
            - open-mixtral-8x22b
            - open-mixtral-8x7b
            - open-mistral-7b
            - mistral-large-latest
            - mistral-small-latest
            - codestral-latest
          targets:
            - setup.api-key
        title: Model Name
      prompt:
        description: The prompt text.
        type: string
        uiOrder: 2
        title: Prompt
      prompt-images:
        description: >-
          The prompt images (Note: The Mistral models are not trained to process images, thus images will be omitted).
        type: array
        uiOrder: 3
        items:
          type: string
        title: Prompt Images
      seed:
        description: The seed.
        type: integer
        uiOrder: 4
        title: Seed
      system-message:
        default: You are a helpful assistant.
        description: >-
          The system message helps set the behavior of the assistant. For example, you can modify the personality of the assistant or provide
          specific instructions about how it should behave throughout the conversation. By default, the model's behavior is set using a generic message
          as "You are a helpful assistant.".
        type: string
        shortDescription: The system message helps set the behavior of the assistant
        uiOrder: 2
        title: System Message
      temperature:
        default: 0.7
        description: The temperature for sampling.
        type: number
        uiOrder: 5
        title: Temperature
      top-k:
        default: 10
        description: >-
          Integer to define the top tokens considered within the sample operation to create new text (Note: The Mistral models does not support
          top-k sampling).
        type: integer
        uiOrder: 5
        title: Top K
      top-p:
        default: 0.5
        description: >-
          Float to define the tokens that are within the sample operation of text generation. Add tokens in the sample for more probable to least
          probable until the sum of the probabilities is greater than top-p (default=0.5).
        type: number
        shortDescription: Float to define the tokens that are within the sample operation of text generation
        uiOrder: 6
        title: Top P
      safe:
        description: Safe generation mode.
        type: boolean
        uiOrder: 7
        title: Safe
    required:
      - prompt
      - model-name
    title: Input
    type: object
  output:
    description: Output.
    uiOrder: 0
    properties:
      text:
        description: Model Output.
        uiOrder: 0
        title: Text
        type: string
      usage:
        $ref: "#/$defs/chat-usage"
    required:
      - text
    title: Output
    type: object
TASK_TEXT_EMBEDDINGS:
  shortDescription: Turn text into a vector of numbers that capture its meaning, unlocking use cases like semantic search.
  description: An embedding is a list of floating point numbers that captures semantic information about the text that it represents.
  input:
    uiOrder: 0
    properties:
      model-name:
        enum:
          - mistral-embed
        example: mistral-embed
        description: The Mistral embed model to be used.
        type: string
        uiOrder: 0
        title: Model Name
        instillCredentialMap:
          values:
            - mistral-embed
          targets:
            - setup.api-key
      text:
        description: The text.
        type: string
        uiOrder: 1
        title: Text
    required:
      - text
      - model-name
    title: Input
    type: object
  output:
    uiOrder: 0
    properties:
      embedding:
        items:
          title: Embedding
          type: number
        description: Embedding of the input text.
        uiOrder: 0
        title: Embedding
        type: array
      usage:
        $ref: "#/$defs/embedding-usage"
    required:
      - embedding
    title: Output
    type: object
