EVENT_CRON_JOB_TRIGGERED:
  title: Cron Job Triggered
  description: An event triggered on a cron job
  configSchema:
    required:
      - cron
    properties:
      cron:
        pattern: ^[0-9*,-/]+\s+[0-9*,-/]+\s+[0-9*,-/]+\s+[0-9*,-/]+\s+[0-9*,-/]+$
        type: string
    type: object
  messageSchema:
    $schema: http://json-schema.org/draft-07/schema
    required:
      - triggered-at
    properties:
      triggered-at:
        description: The ISO 8601 timestamp when the cron job was triggered
        type: string
    additionalProperties: false
    title: Cron job triggered event
    type: object
  messageExamples:
    - triggered-at: '2024-01-01T00:00:00.000Z'
