name: Integration Test (rc) # for release-please PR

on:
  push:
    branches:
      - release-please--branches--main

jobs:
  backend:
    name: Backends
    strategy:
      fail-fast: false
      matrix:
        component: [pipeline, connector, model, mgmt]
    uses: instill-ai/vdp/.github/workflows/integration-test-backend.yml@main
    with:
      component: ${{ matrix.component }}
      target: rc
  console:
    name: Console
    uses: instill-ai/vdp/.github/workflows/integration-test-console.yml@main
    with:
      target: rc
