name: Sync Instill Core Version

on:
  workflow_run:
    workflows: ["Build and Push Images"]
    types:
      - completed
    branches:
      - main

jobs:
  update-version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: instill-ai/instill-core/.github/workflows/update-service-version.yml@main
    with:
      service: pipeline
    secrets:
      botGitHubToken: ${{ secrets.botGitHubToken }}
